### ISSUE TITLE
[QUESTION] Batch messages consumer

### ISSUE THREAD

**Issue by StounhandJ** [mateusjunges/laravel-kafka#102]
Hi, I couldn't figure out what was going on and therefore I want to ask directly. Thank you in advance for the answer.

1. I decided to test a new function with the return of event packets, but for some reason the delay between them does not work.
As you can see, 10 seconds are set, and as a result, there is a delay of 1 to 4 seconds
```php
$consumer = Kafka::createConsumer(['topic'], 'check-consumer)
            ->enableBatching()
            ->withBatchSizeLimit(2)
            ->withBatchReleaseInterval(10000)
            ->withHandler(function (Collection $collection) {
                $this->info(Carbon::now()->second." ".$collection->count());
            })
            ->build();
```
```bash
10 2
10 2
10 2
10 2
11 2
11 2
11 2
11 2
15 1
```

2. The second question. If I do this, I expect that the received message will be considered unsuccessful and there will be no indentation in kafka so that it can be re-processed in the future, but as a result this does not happen.
```php
$consumer = Kafka::createConsumer(['topic'], 'check-consumer', config('trafficMetrics.kafka_brokers'))
            ->enableBatching()
            ->withBatchSizeLimit(2)
            ->withBatchReleaseInterval(10000)
            ->withHandler(function (Collection $collection) {
                throw new Exception();
            })
            ->build();
```
Looking at ConsumerJunges\Kafka\Consumers\Consumer::HandleException, you can see that false should return for RdKafka\Message\Committer::commitMessage.
```php
private function handleException(Throwable $exception, Message|KafkaConsumerMessage $message): bool
    {
        try {
            $this->config->getConsumer()->failed(
                $message->payload,
                $this->config->getTopics()[0],
                $exception
            );

            return true;
        } catch (Throwable $throwable) {
            if ($exception !== $throwable) {
                $this->logger->error($message, $throwable, 'HANDLER_EXCEPTION');
            }

            return false;
        }
    }
```

Maybe I don't understand the indentation work correctly, then I'll listen to how it really works.

**Comment by vsvp21** [comment]
@StounhandJ Hi, sorry for my late answer. Batch is released if and only if withBatchSizeLimit is reached or when withBatchReleaseInterval exceeded. According to documentation "The example below shows that batch is going to be handled if batch size is greater or equals to 1000 or every 1500 milliseconds.". I think there is no need to create a batch for 2 messages, so if you try to put batch site as 1000 or more, then you see the difference

**Comment by mateusjunges** [comment]
Thank you @vsvp21 :heart:
