### ISSUE TITLE
When create a producer

### ISSUE THREAD

**Issue by MohammedGoud** [mateusjunges/laravel-kafka#105]
Unsupported value "snappy" for configuration property "compression.codec": snappy not enabled at build time

**Comment by mateusjunges** [comment]
Hi @MohammedGoud, can you give me more context? Also, please provide the version of this package and the version of librdkafka that you are using·

**Comment by mateusjunges** [comment]
@MohammedGoud `compression.codec` is a producer property. It will be will be ignored by the consumer

**Comment by mateusjunges** [comment]
Closing this due to lack of updates. Feel free to reopen it or create a new issue if your problem persists.
