### ISSUE TITLE
[QUESTION] Have huge messages 

### ISSUE THREAD

**Issue by vahidalvandi** [mateusjunges/laravel-kafka#114]
Hi . I have huge message in second  like 10000  queue how I can use this package for insert db ?

**Comment by mateusjunges** [comment]
Hi @vahidalvandi can you please describe better your problem? I don't know exactly what you want.

You can insert data into the database normally like in any other part of the application, just need to call your model inside your consumer.

**Comment by vahidalvandi** [comment]
I have microservice crypto currency it build very huge data in second like 1000 or 100000 event in second . 
Do laravel kafka handle it in dB insert ?

**Comment by mateusjunges** [comment]
You can use database features inside Kafka consumers like in any other part of your application. This package will only consume messages from the topics you specify in your consumer configuration, so you can save it to the database or do whatever you want with the event being consumed.

**Comment by mateusjunges** [comment]
Closing this due to lack of updates.
