### ISSUE TITLE
[QUESTION] Support SSL Authentication for Consumer?

### ISSUE THREAD

**Issue by tharyono** [mateusjunges/laravel-kafka#127]
Hi,

Is there any support or example for SSL authentication for consumer? So far I only found example for producer in this issue
https://github.com/mateusjunges/laravel-kafka/issues/9

**Comment by gajosu** [comment]
Hello, you can use the `withSasl()` method to set ssl authentication for both consumer and producer

for example:
```php
\Junges\Kafka\Facades\Kafka::createConsumer(['topic'])
    ->withSasl(
        new \Junges\Kafka\Config\Sasl(
            username: 'YOUR_USERNAME',
            password: 'YOUR_PASSWORD',
            mechanisms : 'SCRAM-SHA-256',
            securityProtocol : 'SASL_SSL',
        );
    );
```

**Comment by mateusjunges** [comment]
Thank you @gajosu.

**Comment by M3mbrillo** [comment]
@gajosu  if i only have TSL auth on my cluster, how can I set the .crt, .pem and .key (ssl.key.password, ssl.key.location, ssl.certificate.location, etc) ?
