### ISSUE TITLE
Improve consumer documentation

### ISSUE THREAD

**Issue by mugisham** [mateusjunges/laravel-kafka#131]
Could a concrete example of how the consumer is used and how to use the Kafka: consume command be added? 
Looking at the code isn't getting me there and the examples don't really show how the actual Class structure will be arranged. A good example would be something like the one in the laravel docs: https://laravel.com/docs/9.x/queues. It shows the commands and how they come together with a sample class structure

**Comment by mateusjunges** [comment]
Please check this link https://junges.dev/documentation/laravel-kafka/v1.8/consuming-messages/9-class-structure
