### ISSUE TITLE
[BUG] Timeout ms issue

### ISSUE THREAD

**Issue by riccardobosini** [mateusjunges/laravel-kafka#132]
**Describe the bug**
I created a producer and a consumer in the same project for the same topic.   
The producer works.   
The consumer fails due to a timeout.   
I found out that the timeout is hard-coded here: `vendor/mateusjunges/laravel-kafka/src/Consumers/Consumer.php` at line 150.

```php
    /**
     * Execute the consume method on RdKafka consumer.
     *
     * @throws KafkaConsumerException
     * @throws \RdKafka\Exception|\Throwable
     */
    private function doConsume()
    {
        $message = $this->consumer->consume(2000);
        $this->handleMessage($message);
    }
```
I changed it to `5000` and the consumer started working.  

I suggest to make this value configurable, to adjust it when necessary.

**Comment by mateusjunges** [comment]
Fixed. It is now configurable using the key `consumer_timeout_ms`, in the `config/kafka.php` file. Released on v1.8.7
