### ISSUE TITLE
[BUG] Unable to set some configurations

### ISSUE THREAD

**Issue by riccardobosini** [mateusjunges/laravel-kafka#135]
**Describe the bug**
I think [this](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) is the official list of available configuration for brokers, topic, consumers and producers.  
Each configuration accepts a different kind of value: `string`, `integer`, `boolean`, `float`, `closure`.   
The `->withConfigOption` method accepts as value only `string`.   

**To Reproduce**
1. See [this](https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka-conf.seterrorcb.html) doc for example
2. Define this variable: `$callback = static function (mixed $kafka, int $errorCode, string $errorMsg) {
                throw new Exception($errorMsg, $errorCode);
            };`
3. Build a producer.
4. Use the following method: `->withConfigOption('error_cb', $callback)
5. Try to produce a message.
6. See the error: `TypeError : Junges\Kafka\Producers\ProducerBuilder::withConfigOption(): Argument #2 ($option) must be of type string, Closure given`

**Expected behavior**
For both producers and consumers, I expect one of the following alternatives (or any other else if better):
1. Change the type of the value of the option to `mixed`.
2. Make use of the methods available in this file `vendor/mateusjunges/laravel-kafka/src/Producers/Producer.php` on line 36 (see image attached). The `Conf()` class has some direct methods (`->setErrorCb()`, `->setDrMsgCb()`, `->setConsumeCb()`, `->setRebalanceCb()`, `->setOffsetCommitCb()`). Maybe add next to `->withConfigOption()` something like `->withErrorCb()`, `->withDrMsgCb()`, etc.

**Screenshots**
Image attached to show the available RdKafka\Conf methods.

**Additional context**
Please not that the first proposed solution has to be tested. The second solution shows direct methods that may mean that setting the callback through the related option key is not possible.

![Screenshot from 2022-08-24 13-13-51](https://user-images.githubusercontent.com/23011509/186405269-94345047-910d-4f0c-8c57-7f2827c9fdbe.png)

**Comment by mateusjunges** [comment]
Hey @riccardobosini check #136 please. I'm still thinking in a decent way of implementing tests for this.
