### ISSUE TITLE
[QUESTION] Error creating a Kafka consumer

### ISSUE THREAD

**Issue by cmsedore** [mateusjunges/laravel-kafka#139]
Hi,

I'm having some trouble with the createConsumer facade: what am I getting wrong here?  The first is a cut and paste from the docs, the second is an attempt to supply what the first is asking for...

```php
use Junges\Kafka\Facades\Kafka; 

$consumer = Kafka::createConsumer();
```
```
TypeError: Junges\Kafka\Consumers\ConsumerBuilder::create(): Argument #1 ($brokers) must be of type string, null given, called in /home/laravel/sites/kafkaclient/vendor/mateusjunges/laravel-kafka/src/Kafka.php on line 40
```

```php
use Junges\Kafka\Facades\Kafka;

$consumer = Kafka::createConsumer(config('kafka.brokers'));
```
```
TypeError: Junges\Kafka\Kafka::createConsumer(): Argument #1 ($topics) must be of type array, null given, called in /home/laravel/sites/kafkaclient/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 338
```

**Comment by mateusjunges** [comment]
Hey @cmsedore what `laravel`kafka` version are you using? I tried your code here and it works fine, I'm unable to reproduce this error. Please provide more context so I can actually help you.

**Comment by cmsedore** [comment]
I'm on 1.8 -- I removed and reinstalled the package and things seem to work fine now.  Sorry for the false alarm.
