### ISSUE TITLE
[BUG] `handleBatch` timer issue

### ISSUE THREAD

**Issue by jchambondynadmic** [mateusjunges/laravel-kafka#141]
Hi, I noticed a little problem with batch consuming messages.

Let's say I have a topic full of hundreds of messages, and I want to consume by batches of 20 messages.
What happens : the consumer reads 20 messages, and then 1, then 20, then 1, then 20, 1, 20, 1, etc
It would be better to try to have 20, 20, 20, 20, 20 etc (assuming we can get 20 before timeout of the batch).

The problem is here : 
![image](https://user-images.githubusercontent.com/45685587/191966422-3f3340ef-13c2-4b9c-ba74-926c479fb985.png)

As there is a return, the timer isn't reset if we reach batch max size and the timer continue, so maybe the next time the function will be called the timer will have timeout already ...

Removing the return and add a elseif solves the problem : 
![fix](https://user-images.githubusercontent.com/45685587/191966860-e9bb0128-ca67-4770-bf3b-bcfad9040b54.png)
(Yes, it's the same code in both if... so it could be better, but you got the idea)

Something to fix for next release ?

**Comment by mateusjunges** [comment]
Hey @jchambondynadmic I'll take a look at this, thank you for reporting 🙂

**Comment by mateusjunges** [comment]
Hey @jchambondynadmic can you please try the code in this commit? https://github.com/mateusjunges/laravel-kafka/commit/5bb0a39601d2eeaad6d845e485b0c8d278538de1

**Comment by jchambondynadmic** [comment]
Hey @mateusjunges,

Unfo it'll not works like that.
Because nothing ensure your match() will always have a matching case. So it leads to an UnhandledMatchError "Unhandled match case true".

It would require a default value or use something else than "match"
![image](https://user-images.githubusercontent.com/45685587/193213567-307b159d-26ce-4e04-9c50-36177194d157.png)

**Comment by mateusjunges** [comment]
Yeah I forgot to add the default value. Can you pls add a `default => null` and try one more time? I’ll update the code when I get back home in a few hours 🙂

**Comment by jchambondynadmic** [comment]
It works perfectly with a default => null 🙂

**Comment by mateusjunges** [comment]
@jchambondynadmic fixed and released on v1.8.9 🙂
