### ISSUE TITLE
[QUESTION] Health check when the consumer can start consuming

### ISSUE THREAD

**Issue by TigoCoinmerce** [mateusjunges/laravel-kafka#145]
Hello!

I am trying to figure out if a healthcheck can be configured or added. 

When I start the consumer in our kubernetes cluster it takes a solid 30 seconds for the consumer to start consuming and I want to see if I can add a healthcheck so I can keep the old consumers running until the new one can actually start consuming. This would prevent having message lag when updating our consumers

Is there an easy way to implement a healthcheck for this?

**Comment by mateusjunges** [comment]
Hey @TigoCoinmerce TBH I've never needed this. I'll think about it and get back to you :slightly_smiling_face:

**Comment by TigoCoinmerce** [comment]
Hello! The healthcheck would be amazing! But the problem with the 30 second delay is solved.

**Comment by mateusjunges** [comment]
Hey @TigoCoinmerce do you mind telling me what was the problem with the 30 second delay?

**Comment by TigoCoinmerce** [comment]
> Hey @TigoCoinmerce do you mind telling me what was the problem with the 30 second delay?

Yes, we are using Kubernetes and the package does not respond to the `SIGTERM` signal by default. This caused our pods to be killed by the cluster because they were not terminating. And since our grace period is 30 seconds at the time of discovering. The new ones would not start consuming until the other ones were force killed and the kafka cluster booted them from the consumer group.

**Comment by vadimonus** [comment]
@TigoCoinmerce your problem is that this package is not respecting sigterm. Adding healthcheck will not solve your problem. There will be no guarantee, that your new consumer start consuming, while previous consumer is still working. There can be situation, that previous consumer will continue to consume, and new consumer will not start consuming at all. Two consumers can not work same time on same partition, and broker decides, who will be subscribed, if two consumers whant to consume from same partition.
Right way is add graceful shutdown on sigterm. If process finish gracefully, it will unsubscribe from partition, allowing new consumers to subscribe without waiting. In this case new consumer will subscribe in about a 1 second (time enough for consumer election)

**Comment by TigoCoinmerce** [comment]
> @TigoCoinmerce your problem is that this package is not respecting sigterm. Adding healthcheck will not solve your problem. There will be no guarantee, that your new consumer start consuming, while previous consumer is still working. There can be situation, that previous consumer will continue to consume, and new consumer will not start consuming at all. Two consumers can not work same time on same partition, and broker decides, who will be subscribed, if two consumers whant to consume from same partition.
> Right way is add graceful shutdown on sigterm. If process finish gracefully, it will unsubscribe from partition, allowing new consumers to subscribe without waiting. In this case new consumer will subscribe in about a 1 second (time enough for consumer election)

Hi! Yes I am well aware of that, We have added the SIGTERM functionality so that it gets shutdown properly.

What i had in mind with a health check was to somehow relay the status via a file, command or HTTPGET to Kubernetes informing that is has started properly and working properly. If this at anytime this call fails it'll reboot the consumer.

**Comment by mateusjunges** [comment]
> @TigoCoinmerce your problem is that this package is not respecting sigterm.


Isn't the graceful shutdown functionality working? 🤔

@TigoCoinmerce (if you can share) how have you solved that?

**Comment by vadimonus** [comment]
@m

> > @TigoCoinmerce your problem is that this package is not respecting sigterm.
> 
> Isn't the graceful shutdown functionality working? 🤔
> 
> @TigoCoinmerce (if you can share) how have you solved that?

Consumer should subscribe to signals same way this is done in laravel worker.
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Queue/Worker.php#L675

**Comment by mateusjunges** [comment]
Hey @vadimonus can you please test [this branch](https://github.com/mateusjunges/laravel-kafka/tree/subscribe-to-signals)?

**Comment by vadimonus** [comment]
> Hey @vadimonus can you please test [this branch](https://github.com/mateusjunges/laravel-kafka/tree/subscribe-to-signals)? 

I'm not user of this package, i've just examined it to compare it with my own kafka solution, so i can only review it.
There's no PR so i'll write commens here.

- You shoud'not require ext_pcntl, this will make you package not installable on system without this extention like windows. Better to put it into suggested. See https://github.com/laravel/framework/blob/9.x/composer.json#L146
- Instead you should check and subscribe only if extention is loaded. See https://github.com/laravel/framework/blob/9.x/src/Illuminate/Queue/Worker.php#L130
- There's incorrect indent on line 87

**Comment by mateusjunges** [comment]
> * You shoud'not require ext_pcntl, this will make you package not installable on system without this extention like windows. Better to put it into suggested. See https://github.com/laravel/framework/blob/9.x/composer.json#L146

Yeah 100%, I just wrote a quick first testable version. I'll polish this once I'm back to the office :slightly_smiling_face:

**Comment by mateusjunges** [comment]
Hey @TigoCoinmerce the new v1.12.0 version should solve your problems with the SIGTERM functionality :slightly_smiling_face: 
Just be aware that there are some API changes when upgrading. I added a upgrade guide to the docs page to help with that (nothing really major, just changed a method name and modified its signature). Let me know if this solves your problem!
