### ISSUE TITLE
[QUESTION] Consumer connecting to a Broker that is not available - exception/error

### ISSUE THREAD

**Issue by joaoccmatos** [mateusjunges/laravel-kafka#147]
From what I could find whenever the broker is down, consumer will log the following messages:

`%3|1665746426.651|FAIL|rdkafka#producer-2| [thrd:ssl://broker:9092/bootstrap]: ssl://broker:9092/bootstrap: Failed to resolve 'broker:9092': No address associated with hostname (after 3ms in state CONNECT)
%3|1665746426.651|ERROR|rdkafka#producer-2| [thrd:ssl://broker:9092/bootstrap]: 1/1 brokers are down`

Is there currently, somehow, a way to report or handle this error?

Thanks.

**Comment by mateusjunges** [comment]
Hey @joaoccmatos this logs comes from the rdkafka library, I don't think there's an easy way to intercept it
