### ISSUE TITLE
[QUESTION] Flush returned with error code -185: 'Local: Timed out'

### ISSUE THREAD

**Issue by rafaelzorn** [mateusjunges/laravel-kafka#149]
Hello there,

I am using a docker-compose file to have a local Kafka container.

docker-compose:

![docker compose](https://user-images.githubusercontent.com/5214432/198052783-9e667c84-9b97-429c-886a-48d79fc19655.PNG)

This is my code to do some tests

![Kafka Message](https://user-images.githubusercontent.com/5214432/198054342-4a1053e0-a1b0-46e9-8728-8b14c92ace8c.PNG)

It seems that I always get an Exception with the following error:

`Your message could not be published. Flush returned with error code -185: 'Local: Timed out'`

There arent any messages on the topic.

Am I doing anything wrong?

Thank you in advance

**Comment by mateusjunges** [comment]
Hey @rafaelzorn can you add your full dockerfile as text here so I can try to reproduce it?

**Comment by rafaelzorn** [comment]
Hello @mateusjunges the problem was in my **docker-compose**. Thank's for your time!!!

**Comment by MrFa1n** [comment]
Hey @rafaelzorn, can you tell me how you solved the problem I have a similar one and I still don't know how to solve it?

**Comment by MrFa1n** [comment]
@rafaelzorn can you tell me what you mean by communication between containers and what was wrong there? Thank's!

**Comment by MrFa1n** [comment]
The problem was solved quite elegantly, it was just necessary to specify the parameters in the environment variable. Below is the set of these variables that were used in docker-compose for broker image:
`environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:29092,OUTSIDE://broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG_DIRS: /var/lib/kafka/logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1`

And in kafka.php the name was specified in the config to which the service will be connected, in my case, the name of the service was as follows - 'brokers' => env('KAFKA_BROKERS', '_name_swarm_stack__broker:9092'),
