### ISSUE TITLE
[QUESTION] Call to undefined function Junges\Kafka\Consumers\resolve()

### ISSUE THREAD

**Issue by minhchau2605** [mateusjunges/laravel-kafka#153]
I'm use lumen v9.38.9, php v8.1, mateusjunges/laravel-kafka v1.9.1.
Below is my code in command file. After run command, have exception error.

![image](https://user-images.githubusercontent.com/27195377/199914744-6291fc6b-deab-46fa-aa9a-f3cad8351a39.png)

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'statistic:user-transaction';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'statistic';

    /**
     * Execute the console command.
     *
     * @return void
     * @throws Exception
     * @throws \Exception
     */
    public function handle()
    {
        $consumer = Kafka::createConsumer([config('kafka.topics')])
            ->withAutoCommit()
            ->withHandler(function(KafkaConsumerMessage $message) {
                // Handle your message here
                dump($message);
            })
            ->build();
        $consumer->consume();
    }

**Comment by mateusjunges** [comment]
Hey @minhchau2605 unfortunately this package does not support lumen. I recommend that you switch to laravel, as even the laravel team itself no longer recommend using lumen:


> Note: In the years since releasing Lumen, PHP has made a variety of wonderful performance improvements. For this reason, along with the availability of [Laravel Octane](https://laravel.com/docs/octane), we no longer recommend that you begin new projects with Lumen. Instead, we recommend always beginning new projects with [Laravel](https://laravel.com/).

https://lumen.laravel.com/docs/9.x
