### ISSUE TITLE
[QUESTION] Milliseconds retry parameter not being set when calling flush.

### ISSUE THREAD

**Issue by joanorrit** [mateusjunges/laravel-kafka#155]
Hello,

First of all, thanks for the hard work with a very simple-to-use package! I've had a bit of an issue where some Kafka messages were getting lost. I was using the `send` method in your ProducerBuilder class:

```php
public function send(): bool
{
    $producer = $this->build();

    return $producer->produce($this->message);
}
```

Since I was producing lots of messages, I changed my code to use the `sendBatch` method, which fixed my issue and everything worked smoothly after.

After that, I dug into the problem a bit more and I realized the `flush` method in the Producer class is using the Laravel retry logic:

```php
private function flush(): mixed
{
    return retry(10, function () {
        $result = $this->producer->flush(1000);

        if (RD_KAFKA_RESP_ERR_NO_ERROR === $result) {
            return true;
        }

        $message = rd_kafka_err2str($result);

        throw CouldNotPublishMessage::withMessage($message, $result);
    });
}
```

I was surprised since it seemed to me not as many messages should've been lost for me, even by sending them individually (with the `send` method I shared above) to Kafka with this nice retry logic when flushing. Then I realized, for the flush `retry`, the `sleepMilliseconds` parameter is not being set. So the code doesn't seem to be sleeping for any amount of time before retrying. 
I was just curious about why you took that decision. I was thinking it could be better to sleep for some milliseconds and maybe you could even retry less than 10 times. Being that this method is used for both, the `send` and `sendBatch` methods, I think it would be worth it. 

Also, curious about why you are using the retry Larvel helper here, but not the `retry` method in the Retryable class you created. Wondering if the same retry method should be used everywhere in the package. 

Thanks again for your work!

**Comment by mateusjunges** [comment]
Hey @joanorrit sorry for the late reply, but I'm having a really bush week 😅 
I think the `sleepMiliseconds` makes sense here. Have you tested it with some specific number? TBH I have not faced this issue before so I'm not exactly sure what would be the best choice here.

**Comment by joanorrit** [comment]
Hi @mateusjunges, no worries at all! 
I tested it on my end with 500 milliseconds and it did the trick for me. But is difficult to come up with a number that works for everyone. I believe, the ideal would be to default it to a small number (100 milliseconds) and then add some configuration so each user can configure it to their needs.
But this might be a bit overengineered and if it has to make your library more difficult to use it's probably not worth it. I'd say you could also make it so it sleeps for somewhere between 100 and 500 miliseconds for everyone, which should improve things a bit an not have a negative impact on the package.
At the end, if anyone is sending lots of messages at once, they should fix it by sending messaged in batches, not by retrying to re-flush. So probably a small number makes sense there.

**Comment by mateusjunges** [comment]
> the ideal would be to default it to a small number (100 milliseconds) and then add some configuration so each user can configure it to their needs

Yeah that's what I had in mind. I'll open a PR tomorrow. Thanks!

**Comment by mateusjunges** [comment]
Hey @joanorrit should be fixed now. 

You must add the `flush_retry_sleep_in_ms` key to your `config/kafka.php` file and configure it to the desired amount of time (in ms).

**Comment by joanorrit** [comment]
Hey, this looks great @mateusjunges! Thanks for the quick fix 😄 . Going to make use of this handy config variable!
