### ISSUE TITLE
[QUESTION] Where should I implement the consumer?

### ISSUE THREAD

**Issue by adhenrique** [mateusjunges/laravel-kafka#157]
@mateusjunges how are you?

Where do I need to implement the consumer?
```php
$consumer = Kafka::createConsumer(['topic-1', 'topic-2'], 'group-id', 'broker');
```
Do I need to create a job or something similar in a controller method?

Besides that, to consume messages, do I need to run the `kafka:consume` command?

Thanks for your help :slightly_smiling_face:

**Comment by mateusjunges** [comment]
Hey @adhenrique please use english for issues as it's easier for other people to find answers for common questions.

To answer your questions: 

You can create a console command to consume your messages and then add a process monitor (like supervisor) to ensure that the consumer does not stop running.

Please take a look at [this documentation page](https://junges.dev/documentation/laravel-kafka/v1.9/consuming-messages/9-class-structure) and let me know if it helps :slightly_smiling_face:

**Comment by adhenrique** [comment]
@mateusjunges oh, sorry. I'll keep it in mind. Thanks for translate my question.

Thanks also for sharing this link to the documentation with me. I saw this page, but I didn't associate the title with my need. It might be interesting to implement an example project for my case.

Do you accept a PR?

**Comment by mateusjunges** [comment]
Yeah, feel free to submit a PR

**Comment by mateusjunges** [comment]
Hey @adhenrique I'm closing this as your issue seems to be solved. Feel free to reopen or create another issue if you are still facing problems.
