### ISSUE TITLE
Broker is defined in many places rather than using the config by default

### ISSUE THREAD

**Issue by thetomcake** [mateusjunges/laravel-kafka#16]
I noticed that both of the core methods on the facade publishOn and createConsumer both have a required parameter of broker/brokers. However the config file has a brokers key but the only place this is used is in the KafkaConsumerCommand.

This doesn't seem very laravely. I would suggest that removing that broker/brokers parameter requirement and using the brokers defined in the config would make the library easier to use.

Obviously specific brokers/broker can be defined by using a setBroker(s)/withBroker(s) method on the class or by an optional constructor parameter.

Please can you confirm if there is reasoning behind this design decision. Happy to assist if possible.

**Comment by mateusjunges** [comment]
Hi @thetomcake, i think i have already clarified your questions [here](https://github.com/mateusjunges/laravel-kafka/issues/15#issuecomment-967321458). I'm closing this and keeping #15 for now.
