### ISSUE TITLE
[QUESTION] How to inject instances on handlers?

### ISSUE THREAD

**Issue by ararog** [mateusjunges/laravel-kafka#162]
Is it possible to inject something like a repository instance in a message handler? Or is this only possible using closure approach?

**Comment by mateusjunges** [comment]
Hey @ararog :wave: 
Can you please provide more details? Not sure if I got your point. If you can provide code samples somehow, it'd be helpful :slightly_smiling_face:

**Comment by ebrahimradi** [comment]
I guess he means something like this
`
class TopicHandler implements HandlerInterface
{
    private SomeInterface $something;
    public function __construct(SomeInterface $something)
    {
        $this->something = $something;
    }
    public function __invoke(KafkaConsumerMessage $message): void
    {
    }`

So by constructor , you can inject into handlers. 
AND it is impossible to inject by __invoke method.

**Comment by mateusjunges** [comment]
@ebrahimradi @ararog can you describe a use case for this? I never needed to inject anything into my handlers 🤔

**Comment by ebrahimradi** [comment]
for me also injecting by __invoke method is unknown. However I needed some services to do some jobs based on a message. then I injected those services by __construct() method.
