### ISSUE TITLE
Kafka Pushing Issue 

### ISSUE THREAD

**Issue by k-hasan** [mateusjunges/laravel-kafka#170]
I am trying to implementing the kafka on my laravl project. I run the project on postman then getting following issue. 

{
    "message": "Undefined constant \"Junges\\Kafka\\RD_KAFKA_PARTITION_UA\"",
    "exception": "Error",
    "file": "/public_html/vendor/mateusjunges/laravel-kafka/src/AbstractMessage.php",
    "line": 9,
    "trace": [

**Comment by mateusjunges** [comment]
Hey @k-hasan please take a look at https://github.com/mateusjunges/laravel-kafka/issues/39
