### ISSUE TITLE
[QUESTION] queable consumer handler

### ISSUE THREAD

**Issue by ebrahimradi** [mateusjunges/laravel-kafka#176]
Hi,

I guess the consumption is happening in serial way so when handling of a message finished , then we pick the next message in kafka. Am I thinking correctly?

so how I can make it faster?
should I use some queueable jobs and dispatch them in the handler?
or there are any other tricks? :D 
if there is no trick, 

so I guess good to have other method for consumer instead of `->withHandler($handler)` and then we can say   `->withQueueableHandler($job)`

**Comment by mateusjunges** [comment]
Hey @ebrahimradi :wave: 

>I guess the consumption is happening in serial way so when handling of a message finished , then we pick the next message in kafka. Am I thinking correctly?

Yes :+1: 

> so how I can make it faster?
should I use some queueable jobs and dispatch them in the handler?

Yes, using queueable jobs inside the handler is possible, up to you if you need this in your application :slightly_smiling_face: 

I'm already thinking about a `queueable` handler, but I think it'd be better to make it work as it already works today, but adding a interface to the handler, like Laravel's `ShouldQueue` interface. I'll try to implement that over the weekend :slightly_smiling_face:

**Comment by mateusjunges** [comment]
Ok, I think I got a first working version here:
![image](https://user-images.githubusercontent.com/19756164/219877561-e9025b15-a930-43f7-b86b-5d4fd6f932f6.png)

**Comment by ebrahimradi** [comment]
great @mateusjunges , please let me know if i can help with that.

**Comment by ebrahimradi** [comment]
One more question:
is consuming Sync or Async?
I mean can I consume more than one topic in my commands? something like:

```
$consumers = [];
foreach ($topics as $topic) {
                $handler = handlerFor($topic);
                $consumer = consumerFor($topic, $handler);
                $consumers[] = $consumer;
                $consumer->consume();
            }
```

so does this loop run for the next topics? I tested seems answer is No.

So how can I do that? Is it supported in this plugin or should I use some tools like [how-to-make-async-functions-in-php](https://www.geeksforgeeks.org/how-to-make-async-functions-in-php/) ?

**Comment by mateusjunges** [comment]
@ebrahimradi as [per de documentation](https://junges.dev/documentation/laravel-kafka/v1.12/consuming-messages/1-creating-consumer), you can consume more than one topic in your consumer. However, you will have only one consumer for each command. When you can `consume` on the `Consumer` instance, it will run a loop that keeps listening for new messages until the consumer is stopped, so your foreach example will run for the first consumer but not for the second.

You can consume more than one topic in you consumer by adding the list of topics as an array when creating the consumer:

```php
public function handle(): int
{
    $consumer = Kafka::createConsumer(['test-topic', 'test-topic-2'])
        ->withHandler(new Handler())
        ->build();
        
    $consumer->consume();
        
    return Command::SUCCESS;
}
```

This is the example of the consumed messages, on for each topic:

![image](https://user-images.githubusercontent.com/19756164/220162634-b957c79d-82b8-4a1f-a7dc-12fe71f6bfd1.png)

**Comment by ebrahimradi** [comment]
Thanks for clear answer. Got it, just one problem, each topic has different handler, so cannot pass array of topic and only one handler 🤔 
I guess not bad to pass associated array topic=>handler to a new interface for cusumer.
so we can say `Kafka::createConsumerForManyTopics(['test-topic'=>new Handler() , 'test-topic-2'=>new Handler()])->build();`
then this feature with queable handlers can match perfectly 👍  

what do you think?

**Comment by mateusjunges** [comment]
To be honest I don't like the idea, also never had this use case. It's not that easy to setup multiple consumers within a single command. It's much easier to just create a command to each topic you want to consume (or listen to multiple topics in the same consumer if they have the same handler).

**Comment by ebrahimradi** [comment]
@mateusjunges , one thing comes to my mind before adding this feature, 
if we put them in queue, then it means we do not put the messages in DLQ anymore, so queue handler is responsible to push/produce message into the DLQ topic. right?

**Comment by mateusjunges** [comment]
> if we put them in queue, then it means we do not put the messages in DLQ anymore
Yes. If the handler is queued then the message will not go to DLQ and the offset will be committed right after pushing the job to the queue.
