### ISSUE TITLE
Why KafkaConsumerMessage contract marked as @internal 

### ISSUE THREAD

**Issue by kuudr** [mateusjunges/laravel-kafka#178]
Hi there!

Why KafkaConsumerMessage contract and some more contacts marked as @internal  in versions greater than 1.7 ?

Which flow i need to use for consuming messages ? 

![Снимок экрана 2023-02-21 в 19 43 53](https://user-images.githubusercontent.com/24694506/220407324-5ce7d732-dc80-43cb-b79b-9fa17ca3a5b8.png)

**Comment by mateusjunges** [comment]
Hey @kuudr I marked other contracts as internal, probably a mistake. Will fix soon :pray:

**Comment by mateusjunges** [comment]
@kuudr fixed on v1.12.2, thanks!
