### ISSUE TITLE
[BUG] Kafka::assertPublishedOn not working when producing batch messages

### ISSUE THREAD

**Issue by behzadev** [mateusjunges/laravel-kafka#179]
**Describe the bug**
Kafka::assertPublishedOn works when producing messages but is not working when producing batch messages.

**To Reproduce**
Produce a message batch and send it, on tests assert that using `Kafka::assertPublishedOn('topic', 1)`, it will fail while `Kafka::assertPublished()` and `Kafka::assertPublishedTimes(1)` work. it seems there is a problem with topic name in this situation using `Kafka::fake()`;

**Code Examples**
```php
$message = new Message(
        headers: ['header-key' => 'header-value'],
        body: ['key' => 'value'],
        key: 'kafka key here'  
);

$messageBatch = new MessageBatch();
$messageBatch->push($message);
$messageBatch->push($message);

$producer = Kafka::publishOn('some-kafka-topic')
        ->withConfigOptions(['key' => 'value']);

$producer->sendBatch($messageBatch);

Kafka::assertPublishedTimes(2); // <====== this works just fine
Kafka::assertPublished(); // <====== this works just fine
Kafka::assertPublishedOnTimes('some-kafka-topic', 2); // <====== this fails
Kafka::assertPublishedOn('some-kafka-topic'); // <====== this fails
```

**Comment by mateusjunges** [comment]
Hey @behzadev thanks for reporting. Fixed on v1.12.3 🙂
