### ISSUE TITLE
[QUESTION] possible to change rdkafka values

### ISSUE THREAD

**Issue by 3xc3ption** [mateusjunges/laravel-kafka#185]
Hi,
is it possible to pass or change the rdkafka values like "request.required.acks / acks / request.timeout.ms".
If so, how?

best regards

**Comment by mateusjunges** [comment]
Hey @3xc3ption try the `->withConfigOption('property-name', 'property-value')` method as described in the documentation. 
This method accepts a property name (the config name) and a property value (the config value).
