### ISSUE TITLE
Updating avro cached registry during consuming if message decode failed

### ISSUE THREAD

**Issue by ebrahimradi** [mateusjunges/laravel-kafka#191]
During consuming, if producer uses an updated avro schema, then consumer cannot consume it. 

I suggest to refresh the avro cache registry One time if message couldn't be able to decoded.

**Comment by mateusjunges** [comment]
Hey @ebrahimradi I just read your comments on the other issue (linking it here for context)

https://github.com/mateusjunges/laravel-kafka/issues/4#issuecomment-1408565522
https://github.com/mateusjunges/laravel-kafka/issues/4#issuecomment-1486699101

However, I'm not very experienced in AVRO serializing (used it only once before tbh). Are you able to submit a PR?

**Comment by ebrahimradi** [comment]
I am not experienced also :D 
I try to figure it out and submit a PR ;-)

**Comment by ebrahimradi** [comment]
I like to close this, reason:
if we need a real time schema, better to use a non cached registry.
I guess app should consider this and handle it in other places and with other manners like re-read the cache-registry and other things.
