### ISSUE TITLE
Error: Your message could not be published

### ISSUE THREAD

**Issue by wbvdeveloper** [mateusjunges/laravel-kafka#195]
Hello,
I can not publishing to kafka. Why? What should I do?
![image](https://user-images.githubusercontent.com/91959409/232484330-b70ab4ed-25d5-419c-b205-0b9ed5c31ae1.png)

**Comment by gvillela7** [comment]
Hello,
I'm having the same error. Kafka Service is on, I can create topics, check topics and run consumers.
I'm trying to publish messages like this:
 $message = new Message(
            body: json_encode($myArray),
        );
        $result = Kafka::publishOn('mytopic', 'kafka:9092')->withMessage($message);
        dd($result->send());

"error": "Your message could not be published. Flush returned with error code -185: 'Local: Timed out'"

@wbvdeveloper Did you get it resolved?
