### ISSUE TITLE
[QUESTION] How to commit only the last message of each batch

### ISSUE THREAD

**Issue by tbessenreither** [mateusjunges/laravel-kafka#196]
Hi,

for our project we want to implement a process that commits only the last message of a received Batch to save on roundtrip delay but also have every handled batch reliably marked as received.
As far as i can see, the Consumer class sends each message to the Committer and the Consumers commit methods are private.

Is there a known way to achieve this behaviour?

Greetings
Tobias

**Comment by mateusjunges** [comment]
Hey @tbessenreither this issues looks very specific to your use case, and without further examples I can't debug or work on a solution. Closing this for now.
