### ISSUE TITLE
[QUESTION] Swapping Security For Local/Prod

### ISSUE THREAD

**Issue by nickpoulos** [mateusjunges/laravel-kafka#198]
Our local docker environment has a Kafka service that we want to keep with minimal security settings, ex: PLAINTEXT, no SASL.  

On production, we use the proper security mechanisms, SASL-SCRAM + SASL User/Pass.  Ideally we would use environment variables + config files to set this up.   

Something like: 

```php
$producer = Kafka::publishOn(config('kafka')['topic.name'], config('kafka')['kafka.server']['metadata.broker.list'])
                ->withConfigOptions([
                    'metadata.broker.list' => config('kafka')['kafka.server']['metadata.broker.list'],
                    'security.protocol' => config('kafka')['kafka.server']['security.protocol'],
                    'sasl.mechanism' => config('kafka')['kafka.server']['sasl.mechanism'],
                    'sasl.username' => config('kafka')['kafka.server']['sasl.username'],
                    'sasl.password' => config('kafka')['kafka.server']['sasl.password'],
                    'partitioner' => config('kafka')['kafka.server']['partitioner'],
                ]);
```

Then we just make sure to set the SASL_MECHANISM / SASL_USERNAME / SASL_PASSWORD to null via config/env. 

However it seems like Kafka does not like this, and if it sees the `sasl.mechanism` key in its config object, it will error and complain about an invalid value (this happens for null, false, empty string ,etc).  

```php
  Invalid value for configuration property "sasl.mechanisms": (null)

  at vendor/mateusjunges/laravel-kafka/src/Producers/Producer.php:39
     35▕     {
     36▕         $conf = new Conf();
     37▕
     38▕         foreach ($options as $key => $value) {
  ➜  39▕             $conf->set($key, $value);
     40▕         }
     41▕
     42▕         foreach ($this->config->getConfigCallbacks() as $method => $callback) {
     43▕             $conf->{$method}($callback);


  Tests:  4 failed
```

Unless I am missing something, it seems like the only solution currently seems to be to do a manual environment check and only include those keys on production.  

Either that, or we can modify the `withConfigOptions` to filter out the null values. I am happy to make a PR to add this code, but I wanted to run this by everyone here first. 

Did I miss something obvious? How are you guys handling similar use cases?

Thanks

**Comment by mateusjunges** [comment]
Hey @nickpoulos I just added the laravel `Conditionable` trait to the `ProducerBuilder` and `ConsumerBuilder` in the v2.x branch, so you can do something like this:

```php
$producer = Kafka::publishOn(config('kafka')['topic.name'], config('kafka')['kafka.server']['metadata.broker.list'])
    ->when(config('app.environment') === 'production'), function (ConsumerBuilder $builder) {
        $builder->withConfigOptions([
            'metadata.broker.list' => config('kafka')['kafka.server']['metadata.broker.list'],
            'security.protocol' => config('kafka')['kafka.server']['security.protocol'],
            'sasl.mechanism' => config('kafka')['kafka.server']['sasl.mechanism'],
            'sasl.username' => config('kafka')['kafka.server']['sasl.username'],
            'sasl.password' => config('kafka')['kafka.server']['sasl.password'],
            'partitioner' => config('kafka')['kafka.server']['partitioner'],
        ]);
    });
```

Would this solve your issue?
