### ISSUE TITLE
Long term

### ISSUE THREAD

**Issue by renatocosta** [mateusjunges/laravel-kafka#20]
Hi,

Can this library read many messages per second to the same consumer for the long term?
I recently used the Supervisor to guarantee long life over consumer connections.

Best,

**Comment by mateusjunges** [comment]
Hi @renatocosta, i normally use supervisor to run the laravel command responsible for consuming the kafka topic, to ensure the background command is always up and running.

**Comment by renatocosta** [comment]
Thank you @mateusjunges
