### ISSUE TITLE
[FEATURE REQUEST] Event dispatching

### ISSUE THREAD

**Issue by ebrahimradi** [mateusjunges/laravel-kafka#200]
I know version 2 will be out soon.

I just want to add, in addition of before and after consume mindset that we discussed previously, it is really good to have some events dispatching.

for example consumer stopped because of last message consumed. or consumer stopped.(and these events can have good informations)

for this particular example, we can not use onStopCallback because it would be called even there is other problems not only because of last message consumed.

or when error happens and it wants to go to dlq, it can dispatch an event instead!(or in addition)

I like to know your comments :-)

**Comment by mateusjunges** [comment]
I'm already working on this for v2, and there are some events added already in the v2.x branch. Do you have any specific ones in mind?

**Comment by ebrahimradi** [comment]
thanks @mateusjunges , 
sorry I was on holiday. yes I saw it, it's good enough to start with that. Will read and participate in it later.
