### ISSUE TITLE
Broker: Specified group generation id is not valid

### ISSUE THREAD

**Issue by DevHeaven** [mateusjunges/laravel-kafka#202]
My project connects to a Kafka broker and consumes messages. It has been running fine for a long time , but now has started to throw exceptions and is no longer correctly working.

I keep getting "Broker: Specified group generation id is not valid"

I know this is caused by trying to commit with AutoCommit() while not being part of the group anymore, but I have no idea how/what to configure in the Kafka client in order to have it re-instate the membership to the group.

Here is an extract of the error

`
object(RdKafka\Exception)#1347 (7) {
  ["message":protected]=>
  string(50) "Broker: Specified group generation id is not valid"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(22)
  ["file":protected]=>
  string(72) "/var/www/vendor/mateusjunges/laravel-kafka/src/Commit/KafkaCommitter.php"
  ["line":protected]=>
  int(20)
  ["trace":"Exception":private]=>
  array(31) {
    [0]=>
    array(6) {
      ["file"]=>
      string(72) "/var/www/vendor/mateusjunges/laravel-kafka/src/Commit/KafkaCommitter.php"
      ["line"]=>
      int(20)
      ["function"]=>
      string(6) "commit"
      ["class"]=>
      string(21) "RdKafka\KafkaConsumer"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        object(RdKafka\Message)#911 (10) {
          ["err"]=>
          int(0)
          ["topic_name"]=>
          string(19) "DeliveryTrackingLog"
          ["timestamp"]=>
          int(1683470753552)
          ["partition"]=>
          int(2)
`

**Comment by ebrahimradi** [comment]
Hi @DevHeaven ,

may I know you use which version? and what is you config file and env?

**Comment by alruhmi** [comment]
@ebrahimradi Hi. I get this issue too.
![image](https://github.com/mateusjunges/laravel-kafka/assets/47394493/37df0485-cce7-4a4c-bebd-2b1ed8827fed)

version v1.11
KAFKA_OFFSET_RESET=earliest
KAFKA_MAX_POLL_INTERVAL_MS=300000
KAFKA_MAX_PARTITION_FETCH_BYTES=1048576

```php
$consumer = Kafka::createConsumer()
      ->withAutoCommit(false)
      ->withConsumerGroupId($consumerGroupId)
      ->subscribe($this->getTopic()->value)
      ->withHandler(function (Message $message): void {
             // handle message
      })
      ->withOptions([
            'client.id' => config('app.hostname'),
            'max.poll.interval.ms' => config('kafka.max_poll_interval_ms'),
            'max.partition.fetch.bytes' => config('kafka.max_partition_fetch_bytes'),
      ]);

if (config('kafka.enable_sasl')) {
    $consumer
        ->withOptions([
            'ssl.ca.location' => config('kafka.ssl_ca_location'),
        ])
        ->withSasl(new Sasl(
            username: config('kafka.user'),
            password: config('kafka.password'),
            mechanisms: config('kafka.mechanisms'),
            securityProtocol: config('kafka.security_protocol')
        ));
}

$this->consumer = $consumer->build();

$this->consumer->consume();

**Comment by alruhmi** [comment]
my consumer group id  - Showcase_integration_normalized-price-and-rest-v3

i tried with autocommit true its ok. but offset was not commited

**Comment by ebrahimradi** [comment]
as I said, hyphen char is not allowed to be in consumer group id. try with simple one like "testid" with autocommit true. and reply back please

**Comment by alruhmi** [comment]
the problem was that there were not enough resources for the supervisor Pod in k8 cluster. as a result of which the consumer stopped with SIGKILL

**Comment by DevHeaven** [comment]
Unfortunately I have not yet been able to resolve this :-( 
I do want to mention that this deployment is running on Nomad (Hashicorp)

I keep getting this error "Broker: Specified group generation id is not valid" . The consumer then seems alienated . It still is registered on the broker as a consumer, but it doesn't process anymore messages, it just throws this error.

The group name does not contain any spaces, underscores or other strange characters.
It has a simple name "mlceddconsumer"

I have no idea where to look further, I'd love any tips that could help
