### ISSUE TITLE
Configuring a certificate for a consumer

### ISSUE THREAD

**Issue by ianrothmann** [mateusjunges/laravel-kafka#208]
Hi there,

Thanks for a great library!

I have one question. I get the following error when consuming:

```
/bootstrap: SSL handshake failed: error:0A000086:SSL routines::certificate verify failed 
```

My code is:

```
  $consumer = \Junges\Kafka\Facades\Kafka::createConsumer()
            ->withSasl(new \Junges\Kafka\Config\Sasl($user,$pwd,'PLAIN','SASL_SSL'))
```

This is because I need to install the certificate for the broker. I have the certificate. Where do I specify the path?

Kind regards,

Ian

**Comment by mateusjunges** [comment]
Hey @ianrothmann 👋 

Try specifying config options like in the following snippet please:


```php
->withConfigOptions([
    'security.protocol' => 'ssl',
    'ssl.ca.location' => 'path/to/cacert.pem',
    'ssl.certificate.location' => 'path/kafka.crt',
    'ssl.key.location' => 'path/kafka.key'
]);
```
