### ISSUE TITLE
How to use `laravel-kafka` with laravel commands

### ISSUE THREAD

**Issue by renatocosta** [mateusjunges/laravel-kafka#21]
Hi,

Is there any example of the implementation of this library for the Laravel command?

Best,

**Comment by mateusjunges** [comment]
Hi @renatocosta, i'm building and example project using this library. Will make it public as soon as it's ready, but for now, you can create a command something like this:

```php

class ConsumeXKafkaTopic extends Command
{
    protected $signature = 'kafka:consume-X-topic';

    protected $description = 'Consume messages from kafka topic X';

    public function handle()
    {
        $consumer = ConsumerBuilder::create(config('kafka.brokers'), 'your-group-id', ['X-topic'])
            ->withHandler(new XTopicConsumer())
            ->withAutoCommit()
            ->build();

        $consumer->consume();
    }
}

**Comment by mateusjunges** [comment]
Hi @renatocosta, i'm building and example project using this library. Will make it public as soon as it's ready, but for now, you can create a command something like this:

```php
class ConsumeXKafkaTopic extends Command
{
    protected $signature = 'kafka:consume-X-topic';

    protected $description = 'Consume messages from kafka topic X';

    public function handle()
    {
        $consumer = Kafka::createConsumer()
            ->subscribe('X-topic')
            ->withConsumerGroupId('your-group-id')
            ->withHandler(new XTopicConsumer())
            ->withAutoCommit()
            ->build();

        $consumer->consume();
    }
}
```

**Comment by renatocosta** [comment]
Thank you again @mateusjunges 

By the way, When I used Enqueue lib had a class processor to keep on reading the messages 24/7.
Is there in this library anything like that?

**Comment by mateusjunges** [comment]
I think enqueue use [`queue-interop`](https://github.com/queue-interop/queue-interop) to do this. I haven't tested it so can't confirm it works with this library.

**Comment by renatocosta** [comment]
That's right.
If I understand correctly the **ConsumeXKafkaTopic** class would be called manually via the command line so that reading a new message?

**Comment by mateusjunges** [comment]
Yes, but i use supervisor to run the command in background for me.

**Comment by renatocosta** [comment]
I don't know as you implemented it but I think that it would be a reusable class to be derived from another one.

`class ConsumeXKafkaTopic extends Command
{
    protected $signature;

    protected $description;

    protected string $topicName;

    protected $groupId;

    protected $topicConsumerHandler;

    public function handle()
    {
        $consumer = Kafka::createConsumer()
            ->subscribe($this->topicName)
            ->withConsumerGroupId($this->groupId)
            ->withHandler($this->topicConsumerHandler)
            ->withAutoCommit()
            ->build();

        $consumer->consume();
    }
}`

final class ConsumeUsers extends ConsumeXKafkaTopic
{
    public function __construct()
    {
     parent::signature = ' kafka:consume-users-topic';
     parent::description = 'Consume messages from kafka topic Users';
     parent::topicName = 'users';
     parent::topicConsumerHandler = new XTopicConsumer();
     parent::groupId = 'UserGroups';
    }

    public function handle()
    {
      parent::handle();
    }
}

Just an idea.

**Comment by mateusjunges** [comment]
This library doesn't provide the command to consume messages, so you are free to implement it whatever way you think is better, but yeah, if all consumers looks like this, it's a good implementation.
