### ISSUE TITLE
[QUESTION] Kafka broker list, How to produce on them 

### ISSUE THREAD

**Issue by sultz8** [mateusjunges/laravel-kafka#213]
```php
$producer = \Junges\Kafka\Facades\Kafka::publishOn('topic', 'broker1')
        ->withConfigOptions(config('kafka.producer.global'))
        ->withMessage((new Message())->withBody([]));
```
I want to produce a message, but I have 3 brokers. In RdKafka package I just give a certain config ('metadata.broker.list'), so it will determine on which broker ,message will be sent.
How I can implement it via your package?

**Comment by mateusjunges** [comment]
Hey @sultz8 👋 you can specify your broker list as the second argument of `publishOn` method or define it in the configuration file: https://github.com/mateusjunges/laravel-kafka/blob/ee80f1e7cf3bdd95618fa0cc392d8e186355bc10/config/kafka.php#L7

**Comment by sultz8** [comment]
> Hey @sultz8 👋 you can specify your broker list as the second argument of `publishOn` method or define it in the configuration file:
> 
> https://github.com/mateusjunges/laravel-kafka/blob/ee80f1e7cf3bdd95618fa0cc392d8e186355bc10/config/kafka.php#L7

O thanks a lot!
