### ISSUE TITLE
Kafka transaction when having multiple pushs

### ISSUE THREAD

**Issue by bmohammed0227** [mateusjunges/laravel-kafka#217]
Hii there,
First of all, i appreciate your contribution for the laravel community !! i wanted to know if there's a way or a mechanism to make a transaction when publishing multiple topics after saving in the database, 

`Kafka::publishOn('topic1')->withMessage($message)->send();
            Kafka::publishOn('topic2')->withMessage($message)->send();`

i want to wrap it with something like kafka::transaction, when there's for example a problem in topic2 for some reason (like a time out or any other expection) it will remove the message published in topic2 or to send another message automatically to cancel it.

Any advice ?
Thank you in advance.

**Comment by mateusjunges** [comment]
Hey @bmohammed0227 :wave: currently transaction producer is not implemented in this package. I'm looking into it to add this feature in the near future, but I can't give you an ETA at this moment.

**Comment by mateusjunges** [comment]
Hey @bmohammed0227 I opened a PR #223 to close this issue. Would appreciate if you could take a look on it before it's merged

**Comment by mateusjunges** [comment]
Closing this now. #223 adds this feature and will be available in a few days when I release v2.0
