### ISSUE TITLE
[FEATURE REQUEST] Set configurations globally for producers and consumers

### ISSUE THREAD

**Issue by sultz8** [mateusjunges/laravel-kafka#218]
Hello i need to set below configs.
'enable.idempotence' => 'true',
'acks' => 'all',
'enable.partition.eof' => 'true',
'isolation.level' => 'read_committed',
But this way `->withConfigOptions(config('configs'))` is not suitable for me.
Can I just put above settings in kafka.php? Will it work out?

**Comment by mateusjunges** [comment]
Hey @sultz8 just to understand, why can't you use the `withConfigOption` method?

**Comment by sultz8** [comment]
> Hey @sultz8 just to understand, why can't you use the `withConfigOption` method?

Cause I use kafka in many places, and I don't wanna repeat the same configs

**Comment by mateusjunges** [comment]
That's a fair point. I'll see what I can do to solve this. Requires a bit of work probably, to allow a default set of configurations to be used globally

**Comment by lentex** [comment]
hey @sultz8,
i've had the exact same problem, so i just used a macro for this.

```php
// put this in the boot method of one of your service providers
Kafka::macro('producer', function (string $topic) {
    return $this->publishOn($topic)->withConfigOptions(config('configs'));
});
```

And then you can use it anywhere in your code like this:
```php
Kafka::producer('my-topic')->withBodyKey('my-key', ['foo'=>'bar'])->send();
```

maybe thats a solution you can use for now.

**Comment by mateusjunges** [comment]
Yeah, I'm strongly considering just closing this as resolved and recommending on documentation for devs to go for the macro option when they want to specify global configs for producers/consumers. I don't think it's worth working on it now tbh

**Comment by mateusjunges** [comment]
https://github.com/mateusjunges/laravel-kafka/commit/1565c2f2f0ae0720b1e76330e959bddab92c5535
