### ISSUE TITLE
Can you please tag 1.13.3 including 4 last commits on 1.13.x ?

### ISSUE THREAD

**Issue by jchambondynadmic** [mateusjunges/laravel-kafka#219]
Hi !

We're experiencing slowdown issues with 1.13.2 on PHP 8.2.

On a test sample (pushing data to kafka on a topic with avro serde)
PHP 8.2 => 168 seconds
PHP 8.1 => 2 seconds

The update of flix-tech/avro-serde-php to 2.0 seems to solve the problem. It's made but not tagged yet
https://github.com/mateusjunges/laravel-kafka/compare/v1.13.2...v1.13.x

Thanks !

**Comment by mateusjunges** [comment]
@jchambondynadmic done. I haven't tagged yet because I was expecting to solve an install issue in this release. Anyway, tagged as v1.13.3
