### ISSUE TITLE
[QUESTION] Configuring multiple brokers

### ISSUE THREAD

**Issue by DevHeaven** [mateusjunges/laravel-kafka#224]
Is there any way to configure multiple brokers?
I have a cluster of 3 brokers, but I don't see where I can configure these.

My current code is : 

`        $consumer = \Junges\Kafka\Facades\Kafka::createConsumer(
            [
                'DeliveryTrackingLog',
            ],
            'consumername'.getenv("APP_ENV"),
            'kafka-1uls-fr1.**redacted_privacy**:9092'
        )
`

Ideally, the Brokers section should be an array of brokers , example : 

`        $consumer = \Junges\Kafka\Facades\Kafka::createConsumer(
            [
                'DeliveryTrackingLog',
            ],
            'consumername'.getenv("APP_ENV"),
            ['kafkabroker1:9092','kafkabroker2:9092','kafkabroker3:9092']
        )
`

**Comment by DevHeaven** [comment]
**Unsupported package abandoning**

**Comment by mateusjunges** [comment]
Hey man 👋 it's not an unsupported package, but I still have a full time job that requires more attention than an open source package. I'm still maintaining this on my free time. Feel free to support me on github sponsor program, so I'll have more time available to dedicate to open source work 🙂

**Comment by vipinrao-paytring** [comment]
Hey mateusjunges, i also wanted to configure multiple brokers. can you please help with it.

how do i configure multiple brokers ?
