### ISSUE TITLE
[QUESTION] Broker: Specified group generation id is not valid

### ISSUE THREAD

**Issue by DevHeaven** [mateusjunges/laravel-kafka#225]
**_See also thread https://github.com/mateusjunges/laravel-kafka/issues/202 , but that one was already closed._**

Unfortunately I have not yet been able to resolve this :-( 
I do want to mention that this deployment is running on Nomad (Hashicorp)

I keep getting this error "Broker: Specified group generation id is not valid" every time a Rebalance happens because one or more new consumers are joining the group. The consumer then seems alienated . It still is registered on the broker as a consumer, but it doesn't process anymore messages, it just throws this error.

The group name does not contain any spaces, underscores or other strange characters.
It has a simple name "mlceddconsumer"

I have no idea where to look further, I'd love any tips that could help.

**Comment by DevHeaven** [comment]
@mateusjunges I'd realy love your feedback if you have some time. I'm currently stuck and enable to implement in production because of this issue.

I have also meanwhile dockerized my App and ran it on my workstation. The same issue happens whenever a new consumer is added to the group.

**Comment by DevHeaven** [comment]
I've rewritten my consumer with base LIbrdKafka and ext-rdkakfka and it's working like a charm. **abandoning this package as it's useless in production environments**

**Comment by mihaileu** [comment]
we have the same problem @mateusjunges  do you have some insights ?

**Comment by tuandang-diag** [comment]
@DevHeaven can you share your solution?
