### ISSUE TITLE
[FEATURE REQUEST] Laravel compatible queue support with kafka

### ISSUE THREAD

**Issue by amm834** [mateusjunges/laravel-kafka#227]
If we can use something like below how kafka will be good?

```bash
QUEUE_CONNECTION=kafka
```

# Concept
We'll push messsages to the default topic. And also we will consume from it.

**Comment by mihaileu** [comment]
You can address this to laravel as there's the place to talk about this

**Comment by amm834** [comment]
I don’t think so.

**Comment by mateusjunges** [comment]
Hey @amm834 at this moment I don't have the time/intention to work on this. You can submit a PR if you want, but I think that laravel already ships with other queue drivers that would work much better than kafka, for this pourpose at least.
