### ISSUE TITLE
v1.13.x is now closed for new features

### ISSUE THREAD

**Issue by mateusjunges** [mateusjunges/laravel-kafka#235]
As I am getting close to ship version 2 of this package, it's becoming really hard to merge `v1.13.x` and `v2.x` branches. Since the amount of time I have available to work on open source is really limited right now, I have decided to not accept any PR's adding new features into `v1.13.x`. 

If you are working on a PR for this project that contains a new feature, please use the `v2.x` branch as base.

If you have a PR that fix a bug in `v1.13.x`, feel free to submit it to this branch.

**Comment by amm834** [comment]
When will you release 2.x.x? I found the doc but not the source code? Could you please provide roadmap if you don't mind?

**Comment by mateusjunges** [comment]
@amm834 I'm thinking about releasing it together with laravel 11. Finishing some bugfixing before that. I was traveling for laracon EU this past week and didn't had the time for completing this.

**Comment by amm834** [comment]
Ohh! It okay I have implemented my own kafka queue during these days, I might migrate this with future queue support with this package. Thanks @mateusjunges .

**Comment by mateusjunges** [comment]
Just an update: I'm planning to release v2 on March 12th, together with laravel 11

**Comment by amm834** [comment]
Good to hear, I an eager to migrate all of my queue mechanisms to this pkg.

**Comment by mateusjunges** [comment]
And v2 is out folks https://github.com/mateusjunges/laravel-kafka/releases/tag/v2.0.0

Enjoy!
