### ISSUE TITLE
[QUESTION] Consumers subscribe to Topic using Wildcards or dynamically subscribe to topics

### ISSUE THREAD

**Issue by digidoed** [mateusjunges/laravel-kafka#236]
Hi,

Thanks for the nice job on the `laravel-kafka` project. I am rather new to laravel and Kafka. It seems that there is no support for consumers to subscribe to topics using wildcards / regexp. If there is, could you point me out how to achieve that.
If not or also, I would like to know if it is possible to dynamically subscribe to topics. Now I only got it to work when I start it with:
`php artisan kafka:x-consume`
But to change the subscriptions to topics, I seem to have to reload/ close and restart the consumer from the cli? Or can that be done programmatically?
Maybe the consumer could dynamically subscribe to topics? If so there might be a possibility to use the kafka cli to list the topics, of a wrapper around another script (like python) that could provide a list of topics. 
@https://stackabuse.com/how-to-list-all-kafka-topics/

I see there are also feature requests elsewhere for dynamically subscribing to wildcards, as newly created topics won't always be subscribed to.
I could think of other workarounds/ option to make this possible, but I thought it was wiser to pop this question first, since I am a n00b4fr despite my decades of ... doing stuff... but I was not able to find the answer to a solution digging through the code. I might be unaware of options to do it, which I haven't seen/ understood.
Thanks in advance for your answer/ help.

**Comment by mateusjunges** [comment]
Hey 👋 

You can currently subscribe to topics using regex, but I think it's not documented. Here's an example:

```php
$consumer = Kafka::createConsumer(brokers: 'localhost:9092')
            ->subscribe('^test[0-9]_.*')
            ->withHandler(function (ConsumedMessage $message) {
                $log = [
                    'body' => $message->getBody(),
                    'partition' => $message->getPartition(),
                    'key' => $message->getKey(),
                ];
                $this->info(json_encode($log));
            })->build();

        $consumer->consume();
```

I don't think that topics created after you start the consumer will be subscribed automatically though, you'll have to restart the consumer

**Comment by mateusjunges** [comment]
@digidoed I'm closing this for now, feel free to reopen or open another issue if you still have questions about it 🙂
