### ISSUE TITLE
How this package consumes messages

### ISSUE THREAD

**Issue by giacomomasseron** [mateusjunges/laravel-kafka#238]
Hi,  
I am reading the documentation and I am not able to understand completely how to consume messages.

I understood:

- you create a consumer
- you add options to consumer
- you call `consume` function

What I did not understand is:

- Where do I put this code? (In Laravel console command? a controller?)
- How this package is listening the arriving messages. I mean, kafka will send an HTTPS request to all subscriber. How this laravel handles this request and send the request to this package, to be consumed?
- Related to previous question: what is the purpose of the function of stop listening after last message? Which is the last message of pub/sub pattern?

**Comment by mateusjunges** [comment]
Hey 👋 the documentation contains a [class structure](https://junges.dev/documentation/laravel-kafka/v1.13/consuming-messages/9-class-structure) page, which explains how you can put everything together. 

>Where do I put this code? (In Laravel console command? a controller?)

Basically, a kafka consumer is a laravel console command.

> How this package is listening the arriving messages. I mean, kafka will send an HTTPS request to all subscriber. How this laravel handles this request and send the request to this package, to be consumed?

Kafka will push the message to the broker, and the message will be pulled from the broker by a kafka consumer, which you will create and put in a laravel command. 

> Related to previous question: what is the purpose of the function of stop listening after last message? Which is the last message of pub/sub pattern?

You can use this when reading a topic from the begining (a topic that already has other messages). As soon as you reach the last message in that topic, the consumer should stop itself.

**Comment by giacomomasseron** [comment]
@mateusjunges thanks for your answer, I have a little bit of doubt left:

> > How this package is listening the arriving messages. I mean, kafka will send an HTTPS request to all subscriber. How this laravel handles this request and send the request to this package, to be consumed?
> 
> Kafka will push the message to the broker, and the message will be pulled from the broker by a kafka consumer, which you will create and put in a laravel command.

You need a laravel command always in listening, right?

Something like:  

    php artisan start-my-kafka-consumer

that never stops, always active.

**Comment by mateusjunges** [comment]
Yes, that's correct. I use supervisor to make sure that my consumer is always up and running.

**Comment by mateusjunges** [comment]
Closing this for now, feel free to @ mention me if you still have questions.
