### ISSUE TITLE
Problems with the restart mechanism

### ISSUE THREAD

**Issue by ihuanran** [mateusjunges/laravel-kafka#240]
I see a command that `kafka:restart-consumers`, and I look at the relevant code.   
If there is no timeout between each message, it will not restart?

```php
    protected function checkForRestart(): void
    {
        //If there is no timeout here, it will not be checked the restart timestamp？
        if (! $this->restartTimer->isTimedOut()) {
            return;
        }

        $this->restartTimer->start($this->config->getRestartInterval());
        if ($this->lastRestart !== $this->getLastRestart()) {
            $this->stopRequested = true;
        }
    }
```

**Comment by mateusjunges** [comment]
Hey 👋 

The restart interval is set to 1000 by default. What issues are you having?

https://github.com/mateusjunges/laravel-kafka/blob/fb5c6a48ced74c3a9b1bbbbfba6888c61b49ce91/src/Config/Config.php#L80

**Comment by ihuanran** [comment]
If I execute this command `kafka:restart-consumers`, I have to wait until there are no messages in the queue before I exit the consumer.
According to my test, if there is a message in the queue, the consumer will always be running.
If I use `kill -15 pid`, the consumer is exited after the current message consumption is complete.
The two situations do not seem to have the same effect.

**Comment by ihuanran** [comment]
In addition, because my consumer logic is less than the `$restartInterval`.
see the problem, after consuming a message, it will never time out and will not check the restart timestamp.

In other words, if you use this command `kafka:restart-consumers`, consumers can exit normally when my consumer execution time is greater than `$restartInterval` time, otherwise you will continue to consume messages until there is no message(because when there is no message, it will block for 2 seconds`config.consumer_timeout_ms`), or the execution time is greater than `$restartInterval` time.

I don't know if I made myself clear.

**Comment by ihuanran** [comment]
Ok, my mistake. 
I have understood that this time `$restartInterval` indicates the number of seconds to check to see if a restart is needed, rather than checking after using each message, which seems to be for performance reasons. 
I didn't have enough test data before. 

Anyway, I get it. Thank you.
