### ISSUE TITLE
How do you handle DLQs in the laravel kafka?

### ISSUE THREAD

**Issue by amm834** [mateusjunges/laravel-kafka#242]
I would like to understand the handling mechanism in this package. I have experiment in Nest.js and Kafka + DLQ handling. 
How do you do in this package?
How do you process failed message? 
Do you retry? 
I could not find these concerns in the documentation. I would like to confirm this before I release our application with this beautiful package to the production.

**Comment by mateusjunges** [comment]
@amm834 it depends on how you want to handle it inside your app. You can try to process the message again, store the message in db to perform some kind of debugging later or simply ignoring that message. It depends on your application, there is no rule on how to handle it.

**Comment by mateusjunges** [comment]
I forgot to mention that you have information about the exception that sent the message to the dead letter queue. You can access it using the message headers once it's in the DQL.

```php
$headers = [
    'kafka_throwable_message',
    'kafka_throwable_code',
    'kafka_throwable_class_name'
];
```

**Comment by amm834** [comment]
Thank you @mateusjunges
