### ISSUE TITLE
Facade Fake loses macros

### ISSUE THREAD

**Issue by lentex** [mateusjunges/laravel-kafka#245]
When using macros to define global settings (f.e. sasl, serializer) the facade fake does not know about those macros.

Let's assume you have defined a macro like this:
```php
Kafka::macro('producer', function (string $topic) use ($serializer, $sasl) {
    return $this
        ->publishOn($topic)
        ->withSasl($sasl)
        ->usingSerializer($serializer($topic));
});
```

and then you want to test the producing of a message like this

```php
Kafka::fake();

Kafka::producer($topic)->withMessage(new Message(body: $body))->send();

Kafka::assertPublishedOn($topic);
```
the test will fail with the following message: 

>  Call to undefined method Junges\Kafka\Support\Testing\Fakes\KafkaFake::producer()

A possible solution would be to forward calls (see this PR in Laravel https://github.com/laravel/framework/pull/45988 which solves the same problem https://github.com/laravel/framework/issues/45986)

I've tried to implement it the same way but I had quite the troubles with it and didn't get it to work :(

Would be really cool if you or somebody else could make this happen

**Comment by mateusjunges** [comment]
Hey @lentex thanks for reporting this. I think I didn't ran into this before because I'm not using macros myself. I'll reproduce the issue and work on a fix

**Comment by mateusjunges** [comment]
@lentex I just released v1.13.10 which should fix this. Please test that when you have the time and let me know how it goes.

**Comment by lentex** [comment]
Wow, thanks for adding the passthru so fast! The methods are now defined and can be called, but unfortunately now the "fake" does not work anymore. When I'm using the macro the calls to my Kafka broker are actually sent ("_Your message could not be published. Flush returned with error code -185: 'Local: Timed out'_"). Timed out as there are no brokers defined in my testing environment

**Comment by mateusjunges** [comment]
Looking into this now

**Comment by mateusjunges** [comment]
@lentex releasing v1.13.11 now, should fix this issue

**Comment by lentex** [comment]
Very much appreciated! But I'm afraid that I can verify if my issue is solved not until monday, I'm sorry

**Comment by mateusjunges** [comment]
No problem. I don't like the current solution but couldn't figure out a better way to handle it. I released a new version for now but will try to improve it later.

**Comment by lentex** [comment]
Fortunately I could already verify that your bugfix is working for me. thanks again very much!

**Comment by mateusjunges** [comment]
Thanks for the update!
