### ISSUE TITLE
Schema registry

### ISSUE THREAD

**Issue by renatocosta** [mateusjunges/laravel-kafka#25]
Hello,

Do you already have used Schema registry?

Best,

**Comment by mateusjunges** [comment]
No, just developed the feature and added automated tests. Are you having issues with this?

**Comment by renatocosta** [comment]
No, I do not.

**Comment by renatocosta** [comment]
Actually, I want to allow communications between an App and a Monolith in different tiers.
Thus, I would like to enforce a payload contract in between.

**Comment by renatocosta** [comment]
@nickpoulos Thank you for letting me know.
