### ISSUE TITLE
Producer: performance issue due to flush call

### ISSUE THREAD

**Issue by Ferikl** [mateusjunges/laravel-kafka#251]
Hi thanks for great package.

I have significant issue with performance with producing messages. 
I dig to package code and find that inside

/src/Producers/Producer.php

```
public function produce(ProducerMessage $message): bool
    {
        $this->dispatcher->dispatch(new PublishingMessage($message));

        $topic = $this->producer->newTopic($message->getTopicName());

        $message = clone $message;

        $message = $this->serializer->serialize($message);

        $this->produceMessage($topic, $message);

        $this->producer->poll(0);

        return $this->flush(); <-------------- we have this call
    }
```
Timing **with** this flush() call:
avg time: **120ms**

Timing **w/o** flush() call:
avg tome: **14ms**

**Describe the solution you'd like**
As I discover in other package and solutions they suggest to manually call `flush()` on `__destruct()` or other way.
So I can see 3 way to improve package
- add some config option to use flush on produce or not
- add second param to produce method
- implement new method like `producev` w\o flush call

Thanks a lot!

**Comment by mateusjunges** [comment]
Hey @Ferikl can you point me to other packages/implementations so I can take a look please?

**Comment by mateusjunges** [comment]
I wrote the first version for this. I don't want to completely remove the `flush` call, so I added a call to laravel lottery class to call it for 0.5% of messages only. You can keep the old behavior by passing a `shouldFlush` boolean to the `send` method 

#252

**Comment by mateusjunges** [comment]
Closing this as #252 is merged. Finishing some last improvements before releasing v2

**Comment by DriverCat** [comment]
Hi, thanks for the package, it's great! Today I spent some time to understand, that by default `shouldFlush` is set to false.
Example of producing single message from the docs does not work because of that! Maybe for the case of single message, it's worth adding an example with `shouldFlush` set to true?
