### ISSUE TITLE
Consumer testing not possible when using macros

### ISSUE THREAD

**Issue by lentex** [mateusjunges/laravel-kafka#266]
Hey there, it's me again :)

Testing a consumer works perfectly fine when sticking to the provided example:
https://junges.dev/documentation/laravel-kafka/v1.13/testing/7-mocking-your-kafka-consumer

Although when using a macro for the consumer the code in the **handler callback is not executed at all**.

So instead of
```php
$consumer = Kafka::createConsumer(['mark-post-as-published-topic'])
    ->withHandler(function (KafkaConsumerMessage $message) {
        // business logic
    })->build();
```
I use a macro like this:
```php
$consumer = Kafka::consumer('mark-post-as-published-topic')
    ->withHandler(function (KafkaConsumerMessage $message) {
        // business logic
    })->build();
```

The macro only adds SASL to the consumer:
```php
Kafka::macro('consumer', function (string $topic) use ($sasl) {
    return $this->createConsumer([$topic])->withSasl($sasl);
});
```

Please help!
Thanks in advance

**Comment by mateusjunges** [comment]
Hey @lentex thanks for reporting this. I fixed the issue for v2, will work on a fix for v1.13.x later today.
