### ISSUE TITLE
Mockery\Exception while creating producer

### ISSUE THREAD

**Issue by dilip-E2** [mateusjunges/laravel-kafka#27]
Hello,

I have created producer using below code and i am getting "Mockery\Exception".

I am using Laravel 8 and my OS is Windows 10. 

Below is the code of creating producer.

```php
public function store(Request $request)
{
    $producer = Kafka::publishOn('dev-signup')
            ->withKafkaKey('1qaz2wsx')
            ->withHeaders(['test' => 'test'])
            ->withBodyKey('type',$request->type);

    $producer->send();
        
    return response()->json(['Details published successfully !!']);
}
```

![image](https://user-images.githubusercontent.com/69678247/143245605-c2fa128f-6dac-49cf-a4be-1e027aaeda88.png)

**Comment by mateusjunges** [comment]
Hi @dilip-E2 
The import statement of this exception is wrong and i'm fixing it now, but it means your code could not publish the message to kafka. Can you test your kafka connection using console producers/consumers?

**Comment by dilip-E2** [comment]
Hi @mateusjunges,

In console it is giving me below error about ipv6.

"1637648324.831|ERROR|rdkafka#consumer-1| [thrd:app]: rdkafka#consumer-1: localhost:9092/bootstrap: Connect to ipv6#[::1]:9092failed: Unknown error (after 2003ms in state CONNECT)
"

**Comment by mateusjunges** [comment]
It means your kafka connection isn't working properly, that's why you are getting that exception. Don't know how to fix it but it may have something to do with ipv6

**Comment by mateusjunges** [comment]
@dilip-E2 closing this since it's not updated in past 5 days. Feel free to reopen/create another issue or contact me if you are still facing problems
