### ISSUE TITLE
Undefined constant \"Junges\\Kafka\\RD_KAFKA_PARTITION_UA\

### ISSUE THREAD

**Issue by hellomustaq** [mateusjunges/laravel-kafka#273]
When I tried to hit my end point, I got this message. I checked #39 but unable to find any solutions.
I am using : 
`ubuntu:  23.10`
`PHP:  8.2.10`
`laravel:  10.10`
`mateusjunges/laravel-kafka: 1.13`

### here is my php -i result:
![Screenshot 2024-03-27 at 10 36 51 AM](https://github.com/mateusjunges/laravel-kafka/assets/25515171/e134fec5-63f8-43be-82b4-5749bc44616d)

### here is my php -m result:
![Screenshot 2024-03-27 at 10 38 29 AM](https://github.com/mateusjunges/laravel-kafka/assets/25515171/b35adb69-0727-4175-9fe6-ee154d54d928)

Error Log:
```
"message": "Undefined constant \"Junges\\Kafka\\RD_KAFKA_PARTITION_UA\"",
    "exception": "Error",
    "file": "/var/www/quotation-ms/vendor/mateusjunges/laravel-kafka/src/AbstractMessage.php",
    "line": 9,
    "trace": [
        {
            "file": "/var/www/quotation-ms/vendor/mateusjunges/laravel-kafka/src/Providers/LaravelKafkaServiceProvider.php",
            "line": 47,
            "function": "__construct",
            "class": "Junges\\Kafka\\AbstractMessage",
            "type": "->"
        },
        {
            "file": "/var/www/quotation-ms/vendor/laravel/framework/src/Illuminate/Container/Container.php",
            "line": 908,
            "function": "Junges\\Kafka\\Providers\\{closure}",
            "class": "Junges\\Kafka\\Providers\\LaravelKafkaServiceProvider",
            "type": "->"
        },
...
```

**Comment by hellomustaq** [comment]
@mateusjunges Can you please take a look?

**Comment by mateusjunges** [comment]
Hey man 👋 sorry I've been really busy this past days. I'll take a look over the weekend

**Comment by mateusjunges** [comment]
@hellomustaq do you have a repo where I'm able to reproduce this? I have a fresh laravel app with the package installed and there's no issues there

**Comment by ThangNguyen153** [comment]
Hi, I need to re-open this issue. I got same error with @hellomustaq .
My info are same with the one above:
<img width="395" alt="image" src="https://github.com/mateusjunges/laravel-kafka/assets/20796664/15ed1718-aebd-4c20-a99f-44fe3a7b7baf">

Sorry I can't share the repo. Both CLI and Apache enabled rdkafka. I'm not using php-fpm.
Can you please have a look @mateusjunges ?

**Comment by ThangNguyen153** [comment]
<img width="251" alt="image" src="https://github.com/mateusjunges/laravel-kafka/assets/20796664/522ce91a-39a6-4897-a60a-213e9e06c7d8">
I'm not sure about this but I can't find the value of these constant.

it should have something like this: public RD_KAFKA_PARTITION_UA = -1
but I can't find these values. is this problem related to the library version?
