### ISSUE TITLE
Wrong return type in Junges\Kafka\Config\Config->getCommit

### ISSUE THREAD

**Issue by panaiteandreisilviu** [mateusjunges/laravel-kafka#275]
I get this error when trying to consume messages:

Junges\Kafka\Config\Config::getCommit(): Return value must be of type int, string returned.

The value of commit is "1".

It seems the commit is being cast as a string here: \Junges\Kafka\Console\Commands\KafkaConsumer\Options::getCommit

A possible fix may be to change the return type for **\Junges\Kafka\Config\Config::getCommit** to **int|string|null**, the same as in the constructor.

Command:
php vendor/bin/sail artisan kafka:consume --consumer=App\\Commands\\Consumers\\Kafka\\MyConsumer --topics=my_topic --groupId=my_group --maxMessage=5000 --maxTime=3600

**Comment by panaiteandreisilviu** [comment]
opened a PR: https://github.com/mateusjunges/laravel-kafka/pull/276

**Comment by mateusjunges** [comment]
I'll check it later today, thanks!
