### ISSUE TITLE
Cannot Consume published messages in laravel 11 and php 8.3.6

### ISSUE THREAD

**Issue by eamon-straughn** [mateusjunges/laravel-kafka#277]
**Describe the bug**
Cannot Consume published messages

**To Reproduce**
`$message = new Message(
        //headers: ['header-key' => 'header-value'],
            body: $request,
        //key: 'kafka key here'
        );

        Kafka::publish()->onTopic('backoffice.audit')->withMessage($message)->send();`
1. Using the code above I can send a message and have verified the message is sent
2. Then trying to consume the message and literally it just hangs with no output here is the code

`$consumer = Kafka::consumer()
            ->subscribe('backoffice.audit')
            // ->withBrokers('kafka:9092')
            ->withHandler(function (ConsumerMessage $message, MessageConsumer $messageConsumer){
            $key = $message->getKey();
            $body = $message->getBody();
            $topic = $message->getTopicName();
            $offset = $message->getOffset();

            print_r($offset); echo "\n";

            print_r($body); echo "\n";
/*
            $body = (object)$body;
            $audit = new Audit;
            $audit->client = $body->client;
            $audit->form = $body->form;
            $audit->document = $body->document;
            $audit->where = $body->where;
            $audit->what = $body->what;
            $audit->how = $body->how;
            $audit->when = $body->when;
            $audit->who = $body->who;
            $audit->table = $body->table;
            $audit->changes = json_encode($body->changes);
            $audit->data = json_encode($body->data);
            $audit->save();
            $audit->refresh();

            if($audit->client) {
                if($audit->who) {
                    $client = Client::withTrashed()->where('uuid', $audit->client)->first();
                    $client->lastUpdatedBy = $audit->who;
                    $client->save();
                    $client->refresh();
                }
            }

            if($audit->form) {
                if($audit->who) {
                    $form = Form::withTrashed()->where('uuid', $audit->form)->first();
                    $form->lastUpdatedBy = $audit->who;
                    $form->save();
                    $form->refresh();
                }
            }

            if($audit->document) {
                if($audit->who) {
                    $document = DocumentsRequired::withTrashed()->where('uuid', $audit->document)->first();
                    $document->lastUpdatedBy = $audit->who;
                    $document->save();
                    $document->refresh();
                }
            }
*/

        })->build();
        $consumer->consume();`

**Expected behavior**
It should consume the messages and i should see output of the body and offset of the message

**Comment by mateusjunges** [comment]
looking into this one now

**Comment by panaiteandreisilviu** [comment]
@eamon-straughn  does using ->send(true) resolve your issue?

**Comment by rootcause0** [comment]
> @eamon-straughn does using ->send(true) resolve your issue?

Had the same problem as OP and when I used "true" it fixed my problem, thanks!

**Comment by cvairlis** [comment]
Hello all. Makes sense, flags introduced here: [Improve producer performance by reducing flush calls](https://github.com/mateusjunges/laravel-kafka/pull/252)
Please add a reference at the upgrade guide. Or if we can contribute somehow please advice. :)

**Comment by mateusjunges** [comment]
Hey! I was finally able to reproduce this. Can you please set the `linger.ms` parameter to `0` on your producer? That should remove the need to use the `->send(true)` and you should be able to consume your messages without any problem. Let me know if this solves your issue and I'll update docs then

**Comment by cvairlis** [comment]
@mateusjunges thank you! I will try it, but I cannot figure out how do I change tis `linger.ms` parameter to set it to `0`. Can you please assist?

**Comment by mateusjunges** [comment]
@cvairlis yeah, using `withConfigOption` should do it

```
->withConfigOption('linger.ms', 0)
```

Then, I added a `dd($conf)` in the `setConf` method, and this is the output:

```
$ a app:produce | grep queue.buffering.max.ms
queue.buffering.max.ms: "0"
```

**Comment by jhjvandenbroek** [comment]
Having to set $shouldFlush to true is a breaking change. In my opinion when adding a parameter like this it is best to make it default to true to avoid this.

In any case: Please update the documentation. Currently it is not clear at all this flag needs to be set. This sends users like me into a google loop.

**Comment by aungmyatmoethegreat** [comment]
Setting config and flushing flag are not working in v2.0.

I don't know why flushing become a deal since v2?

```php
    Kafka::publish()
            ->onTopic('saga')
            ->withConfigOption('linger.ms', 0)
            ->withMessage(new Message(body: [
                'name' => fake()->name
            ]))
            ->send(true);
```

**Comment by mateusjunges** [comment]
> Having to set $shouldFlush to true is a breaking change. In my opinion when adding a parameter like this it is best to make it default to true to avoid this.

That's why a new major release was tagged 🙃

**Comment by mateusjunges** [comment]
v2.1.0 should fix this. You no longer have to pass the `shouldFlush` parameter. I also updated the docs about sending single messages (Proucer::send) and multiple messages (Producer::sendBatch).

For single messages, flush is called automatically, but keep in mind that this slows down the producer.
If you need to send multiple messages on one request, please use batching and send them all in once.

**Comment by mateusjunges** [comment]
Feel free to open another issue if your problem persists.

**Comment by jhjvandenbroek** [comment]
It makes sense now. I misread and thought the change was introduced in 2.0.4 but it actually was 2.0.0

I realize this is an open source package and I appreciate your work in developing and documenting it for the Laravel community to use. This is hands down the best Laravel+Kafka implementation out there. Other packages are not Laravel style or are impossible to mock in tests ( Kafka::fake is awesome! ).

I didn't mean to come across rude. I expect to be using this package intensively I would love to get involved and open a PR if I have an idea to contribute.
