### ISSUE TITLE
What do  we need to set for the `--consumer` flag.

### ISSUE THREAD

**Issue by aungmyatmoethegreat** [mateusjunges/laravel-kafka#282]
```bash
php artisan kafka:consume --consumer=??? # class? 
```

https://github.com/mateusjunges/laravel-kafka/blob/a0673a4c1914f5b267fe70f414bff8ed72664eec/src/Console/Commands/ConsumerCommand.php#L17

https://github.com/mateusjunges/laravel-kafka/blob/a0673a4c1914f5b267fe70f414bff8ed72664eec/src/Console/Commands/ConsumerCommand.php#L74

**Comment by mateusjunges** [comment]
It should be the fqcn to the consumer you want to handle the message
