### ISSUE TITLE
[Question/bug] Consuming Tombstones and send it to dlq throws $payload must be of type string, null given

### ISSUE THREAD

**Issue by mhv666** [mateusjunges/laravel-kafka#290]
Hi I was using version 1.13, and recently I updated to 2.0 and this error happen:

Right now If I try to consume a tombstone, aka null payload it throws me this error instead of not throwing any error, I'm not sure if I should include some option with **->withOptions()** or how to proceed with these 🙇🏽 

Here how I build and consume:
![image](https://github.com/mateusjunges/laravel-kafka/assets/11708446/4c05f024-f65b-4b51-ad89-8cf0fb19df1d)

Error throwed:
![image](https://github.com/mateusjunges/laravel-kafka/assets/11708446/55ca537f-91e4-456c-89a2-d342da285f2e)

Thanks for your help

**Comment by mateusjunges** [comment]
hey @mhv666 👋 I pushed a fix for this, let me know if it works
