### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by lufeijun** [mateusjunges/laravel-kafka#3]
![image](https://user-images.githubusercontent.com/20056068/134900402-98df2f2e-c7b8-436a-a9b5-4bf25c472c17.png)

**Comment by mateusjunges** [comment]
Hello @lufeijun 
Which PHP version are you using?

**Comment by lufeijun** [comment]
mac php@ 7.4.24

**Comment by mateusjunges** [comment]
This package requires PHP ^8.0:
```json
"require": {
        "php": "^8.0",
}
```
