### ISSUE TITLE
Undefined constant "Junges\Kafka\RD_KAFKA_PARTITION_UA",

### ISSUE THREAD

**Issue by Dinesh-loma** [mateusjunges/laravel-kafka#302]
Bug information is here.

https://github.com/mateusjunges/laravel-kafka/issues/39#issuecomment-2249496095

@mateusjunges

**Comment by theaungmyatmoe** [comment]
There is no issue after trying this. 
Here you can reference.
https://github.com/myanmarcyberyouths/breeze-microservices

**Comment by mateusjunges** [comment]
I cant reproduce this.
