### ISSUE TITLE
Consumer middlewares cannot be implemented at described

### ISSUE THREAD

**Issue by sash** [mateusjunges/laravel-kafka#303]
**Describe the bug**
The middleware wraps the handler but the handler requires the consumer to be passed in, while the middleware only passes the message on to the next handled and omits the consumer.

**To Reproduce**
Steps to reproduce the behaviour:
1. Implement an empty middleware as described in the docs
2. Run the consumer and have it consume a message
4. See error `Too few arguments to function CLASS::...{closure}(), 1 passed in /MyExampleMiddleware.php on line X and exactly 2 expected"`

**Expected behavior**
To be able to use middlewares as described in the docs

**Additional Notes**
Check out `Junges\Kafka\Concerns\HandleConsumedMessage.php` and consider the fact that the original handle requires two arguments, but the next function only accepts one - the message. That makes it impossible to implement. You need to aither wrap the consumer argument in or pass it down to the middlewares as well (that might be beneficial but harder to use).

Thank you and good job on the module. It makes working with Kafka much more "Laravely" :)

**Comment by sash** [comment]
If you think the way to go is to wrap in the consumer and hide it from the middleware, I will open a MR with the implementation

**Comment by mateusjunges** [comment]
@sash I cant reproduce this. Here's my consumer code:

```php
$consumer = Kafka::consumer(brokers: 'localhost:9092')
            ->subscribe('confluent')
            ->withMiddleware(function (ConsumedMessage $message, callable $next) {
                return $next($message);
            })
            ->withHandler(function (ConsumedMessage $message) {
                $log = [
                    'body' => $message->getBody(),
                    'partition' => $message->getPartition(),
                    'key' => $message->getKey(),
                    'topic' => $message->getTopicName(),
                ];
                $this->info(json_encode($log));
            })
            ->onStopConsuming(function () {
                $this->line('Consumer stopped.');
                $this->newLine();
            })->build();

        $consumer->consume();
```

I also tried with an empty middleware, and in this case I don't see any error, but the message is not consumed, which is expected.

```php
->withMiddleware(function (ConsumedMessage $message, callable $next) {
    return $next($message);
})
```

**Comment by sash** [comment]
My test was done not with an inline function but with a class that implements Middleware - not sure what effect that will have. I will try to create a small script that can reproduce it

**Comment by sash** [comment]
Now I understand the issue better. Its not about the middleware. Its about the fact that in your test your handler has only one argument and in that case everything is OK. But I used the docs handler that actualy has a second argument that is the consumer. If you add that one in your ->withHandler(function (ConsumedMessage $message) { you are going to experience the issue. For me a better approach might be to drop the second argument as you can always use the contaxt to capture the consumer if need be.
