### ISSUE TITLE
Support for php 7.4 and laravel 8

### ISSUE THREAD

**Issue by jeveiga** [mateusjunges/laravel-kafka#307]
Hi,

First of all, thanks for this amazing package! Looks awesome from the documentation I've read.

I have a project that I can't upgrade just yet but I need a solution for an existing problem on my end with our current implementation to interact with kafka topics and I'd love to try your package but from what I've seen, the V2 requires PHP 8.1+ and Laravel 9+.

I know I'm asking about old versions of php and laravel but is there any version of this package that is compatible with PHP 7.4 and Laravel 8?

Thanks 😄

**Comment by mateusjunges** [comment]
Hey @jeveiga 👋 I don't think there are any versions supporting PHP 7.4. As far as I remember, I wrote the first version of this package requiring `php@^8.0`. In the past someone attempted to fork this repo and make it support php 7.4, but I don't know if the fork still exists and if it is still being maintained.
