### ISSUE TITLE
[Question]: Error: Call to a member function shouldFake() on null

### ISSUE THREAD

**Issue by Kussie** [mateusjunges/laravel-kafka#326]
I've been trying to figure out this issue for a few hours now and i am scratching my head trying to find the underlaying cause.

I get the above error when trying to write some tests for my setup, for interest sake i have pared my test back to the following which still throws the error:
```
#[Test]
    public function it_can_read_a_message_from_kafka(): void
    {
        Kafka::fake();

        $this->assertTrue(true);
    }
```

As we can see it is an extremely simple test.  I initially figured it might have something to do with my local setup somewhere, such as the package not being properly installed.  However i am able to successfully use it in my command.  I get this error on both version 2.4.1 and 1.13.13. 

Running on PHP 8.3 and Laravel 11.34.2 

I am guessing i am overlooking something extremely simple or silly at this point.  

Just for the record the code in my command is:
```
Kafka::consumer([$topic])->withHandler(new $transformer)
                ->build()
                ->consume();
```

Which as mentioned seems to work fine.  Both are using the same Facade of `Junges\Kafka\Facades\Kafka`

**Comment by Kussie** [comment]
Nevermind.  I'm an idiot

**Comment by mateusjunges** [comment]
Hey @Kussie 👋 feel free to post the solution here, it might help other people that run into the same issue later on. Also, if you think the docs aren't clear enough on this topic, please let me know

**Comment by Kussie** [comment]
Wasn't an issue with the docs.  It was my stupidity using the wrong TestCase on my tests.  I was using the PHPUnit Testcase instead of the Laravel one, so of course none of the Laravel application was getting loaded as a result.
