### ISSUE TITLE
many deprecations when upgrading to php 8.4

### ISSUE THREAD

**Issue by mihaileu** [mateusjunges/laravel-kafka#329]
**Describe the bug**
Many deprecation warnings when upgrading to php 8.4

```
Deprecated: Widmogrod\Monad\IO\tryCatch(): Implicitly marking parameter $catchFunction as nullable is deprecated, the explicit nullable type must be used instead in /var/www/xxx/vendor/widmogrod/php-functional/src/Monad/IO/errors.php on line 53
```

**To Reproduce**
use php 8.4

**Expected behavior**
Do not now receive deprecartion warnings

**Additional context**
The deprecation are due to this library used by one of your sub packages: https://github.com/widmogrod/php-functional/issues/113
The above library seems unmaintained for 2 years.

**Comment by mihaileu** [comment]
I managed to fix a part of them, there is still a fork managed by you: Deprecated: FlixTech\AvroSerializer\Common\memoize(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used

**Comment by mateusjunges** [comment]
I fixed those issues on packages I maintain. PHP 8.4 was release less than a month ago. We should give some time for the community to work on all those deprecations.
