### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by MarceloSantosCorrea** [mateusjunges/laravel-kafka#33]
Clean installation of Laravel

PHP Version
![Captura de Tela 2021-12-03 às 11 02 57](https://user-images.githubusercontent.com/5748703/144615197-791be8e6-c1f1-4c3e-98f0-63ccf0f166bc.png)

composer.json
![Captura de Tela 2021-12-03 às 11 03 36](https://user-images.githubusercontent.com/5748703/144615294-00d4fabc-93e6-4cf7-9e30-ee7258a0f343.png)

Error message
![Captura de Tela 2021-12-03 às 11 05 01](https://user-images.githubusercontent.com/5748703/144615618-7a7ff1c4-d32e-4dee-ad80-50242e279338.png)

**Comment by mateusjunges** [comment]
Hi @MarceloSantosCorrea, the `composer.json` file had a dependency that should not be there. I removed it and tagged [v1.4.4](https://github.com/mateusjunges/laravel-kafka/tree/v1.4.4). It should work now.

**Comment by rtuin** [comment]
This works by downgrading the `guzzlehttp/psr7` package. I've created a PR here to prevent the downgrading, but it has yet to be reviewed: https://github.com/flix-tech/schema-registry-php-client/pull/66.

**Comment by mateusjunges** [comment]
@rtuin fixed with release 7.5.1 of flix-tech/schema-registry-php-client. Thank you for the PR!
