### ISSUE TITLE
[QUESTION] Error in Docs + Other Considerations for withHandler()

### ISSUE THREAD

**Issue by nickpoulos** [mateusjunges/laravel-kafka#41]
I believe the docs are showing some incorrect syntax when passing around invokable classes as callables. 

Ex: This will bomb because `withHandler` expects a callable, not a string

```php
$consumer = Kafka::createConsumer()->withHandler(MyMessageHandler::class)
```

In order to work, this should be: 

```php
$consumer = Kafka::createConsumer()->withHandler(new MyMessageHandler)
```

#### Suggestions/Thoughts

However the correct syntax is not super useful as designed.  For instance, if our handler class requires any dependencies in the constructor. We have to know the dependencies ahead of time and provide them.  If we can have the handler work with dependency injection and resolve dependencies automatically from the container that would be great. 

Right now the best alternative is to create a closure that calls our processor class. Not a show-stopper but not as nice.  

#### Additional Notes

I would also suggest we make the `$broker` parameter in createConsumer() signature non-nullable and therefore required.  Currently there is no other way to setup the broker config without setting it there, as are missing a `withBrokers()` setter method.

With that being said, I think the `withAutoCommit()` method should accept a boolean that defaults to true.  This would allow us to just pass config vars that automatically set things up without requiring the logic on our end. 

Ex. instead of

```php
$consumer = Kafka::createConsumer(brokers: $config['brokers']);

if ($config['auto_commit']) {
   $consumer->withAutoCommit();
}

```

We can simply do 

```php
$consumer = Kafka::createConsumer(brokers: $config['brokers'])->withAutoCommit($config['auto_commit']);
```

I feel strongly that other config should be setup the same way.  Ex. withSasl should accept nullable-strings

**Comment by mateusjunges** [comment]
@nickpoulos take a look at #42 

> I would also suggest we make the `$broker` parameter in createConsumer() signature non-nullable and therefore required. Currently there is no other way to setup the broker config without setting it there, as are missing a `withBrokers()` setter method.

I prefer to add a `withBrokers` setter here other than making `$broker` required on `createConsumer`. I made it optional because if it's already defined in `config/kafka.php`, you don't want to define it again for each consumer you create, unless it's a different broker, but that's another thing.



> Right now the best alternative is to create a closure that calls our processor class. Not a show-stopper but not as nice.

How do you suggest it should be implemented? If you can add some example code it would be nice.

**Comment by nickpoulos** [comment]
Hey @mateusjunges, whoa very quick pr, much appreciated!

Yea I understand what you mean about `withBrokers`. We have struggled with that little problem as well, how to cleanly separate the server variables from the consumer variables.  But ended up dividing our config/Kafka.php into something like below.  I am still trying to see if this makes sense the way it is split up, but its worth thinking about.  It goes towards the discussions we had in https://github.com/mateusjunges/laravel-kafka/issues/32 

```<?php

return [

    'clusters' => [

        'default' => [
            /*
             | Your kafka brokers url.
             */
            'brokers' => env('KAFKA_BROKERS', 'localhost:9092'),

            'sleep_on_error' => env('KAFKA_ERROR_SLEEP', 5),

            'partition' => env('KAFKA_PARTITION', 0),

            /*
             | Kafka supports 4 compression codecs: none , gzip , lz4 and snappy
             */
            'compression' => env('KAFKA_COMPRESSION_TYPE', 'snappy'),

            'security_protocol' => env('KAFKA_SECURITY_PROTOCOL','plaintext'),

            'sasl_mechanism' => env('KAFKA_SASL_MECHANISM',null),
            'sasl_username' => env('KAFKA_SASL_USER',null),
            'sasl_password' => env('KAFKA_SASL_PASS',null),

            /*
             | Choose if debug is enabled or not.
             */
            'debug' => env('KAFKA_DEBUG', false),
        ]
    ],

    'consumers' => [
        'supply_router' => [

            'topics' => explode(',', env('KAFKA_SUPPLY_ROUTER_TOPIC', 'supply_router')),
            'deadletter_topic' => env('KAFKA_SUPPLY_ROUTER_TOPIC', 'supply_router') . "_deadletter",

            /*
             | Kafka consumers belonging to the same consumer group share a group id.
             | The consumers in a group then divides the topic partitions as fairly amongst themselves as possible by
             | establishing that each partition is only consumed by a single consumer from the group.
             | This config defines the consumer group id you want to use for your project.
             */
            'consumer_group_id' => env('KAFKA_CONSUMER_GROUP_ID', 'group'),

            /*
             | After the consumer receives its assignment from the coordinator,
             | it must determine the initial position for each assigned partition.
             | When the group is first created, before any messages have been consumed, the position is set according to a configurable
             | offset reset policy (auto.offset.reset). Typically, consumption starts either at the earliest offset or the latest offset.
             | You can choose between "latest", "earliest" or "none".
             */
            'offset_reset' => env('KAFKA_OFFSET_RESET', 'latest'),

            /*
             | If you set enable.auto.commit (which is the default), then the consumer will automatically commit offsets periodically at the
             | interval set by auto.commit.interval.ms.
             */
            'auto_commit' => env('KAFKA_AUTO_COMMIT', true),
        ],
    ],
];
```

**Comment by nickpoulos** [comment]
Ah awesome! I have to catch back up on these threads in the morning.  It has been a little nuts at work between the AWS outage + Log4J.  I will check out all these new changes and leave some comments.
