### ISSUE TITLE
[QUESTION] Sent messages may not be completed yet.

### ISSUE THREAD

**Issue by irfanpathanudr** [mateusjunges/laravel-kafka#48]
I have this configuration:

<html>
<body>

lib | version
--|--
ubuntu os | 20.0
PHP Version | 8.0.13
rdkafka version | v5.0.2V
librdkafka version (runtime) | 1.2.1
librdkafka version (build)	| 1.2.1.255
"mateusjunges/laravel-kafka" | ^1.5

</body>
</html>

and my producer code

```php
 $producer = Kafka::publishOn('topic')
    ->withKafkaKey('your-kafka-key')
    ->withKafkaKey('kafka-key')
    ->withHeaders(['header-key' => 'header-value']);

$producer->send();
```

get error  

`Junges\Kafka\Exceptions\CouldNotPublishMessage` Sent messages may not be completed yet.

**Comment by mateusjunges** [comment]
Can't reproduce your error on a fresh laravel installation.

Can you test your kafka connection via console producers/consumers? (Maybe this doc](http://cloudurable.com/blog/kafka-tutorial-kafka-from-command-line/index.html) can help you with that.

**Comment by irfanpathanudr** [comment]
@mateusjunges  thanks for the help me.
Thank you for creating a solid Kafka package.

**Comment by mateusjunges** [comment]
I'm glad i was able to help you!
