### ISSUE TITLE
[QUESTION] Exception No such configuration property: "key"

### ISSUE THREAD

**Issue by maquib** [mateusjunges/laravel-kafka#49]
@mateusjunges can you plz help me on this error is coming when am trying to send message to kafka.

![Screenshot (94)](https://user-images.githubusercontent.com/35573646/146520889-6e558415-361d-45d5-9762-b40f2aff8f28.png)

Here is my code:

```php
/** @var \Junges\Kafka\Producers\ProducerBuilder $producer */
 $producer = Kafka::publishOn('test-topic', 'localhost:9092')
        ->withBodyKey('foo', 'bar')
        ->withConfigOptions(['key' => 'value'])
        ->withKafkaKey('your-kafka-key')
        ->withKafkaKey('kafka-key')
        ->withHeaders(['header-key' => 'header-value'])
        ->send(); // Also to disable debug mode

return response($producer);
```

**Comment by mateusjunges** [comment]
Hy @maquib it means that the `key` property does not exist in kafka. You can [check the available configuration options here](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md). The `key` property is used in docs for example only.

**Comment by maquib** [comment]
@mateusjunges okay thank you for help

**Comment by P-PATHAK** [comment]
HIi @mateusjunges mateusjunges

**Comment by mateusjunges** [comment]
@P-PATHAK please check [this documentation page](https://junges.dev/documentation/laravel-kafka/v1.9/producing-messages/5-publishing-to-kafka). You can add your producer to any part of you app.
