### ISSUE TITLE
[QUESTION]How to cosume a message?

### ISSUE THREAD

**Issue by maquib** [mateusjunges/laravel-kafka#58]
@mateusjunges Here is my producer code and this returning success but i am not able to consume the message to consumer end
```php
 $message = new Message(
    headers: ['apiKey' => '12345'],
    body: ['foo' => 'bar'],
);     

$producer = Kafka::publishOn('test-topic','localhost:9092')->withMessage($message)->send();
```

Here is my consumer code but it is not working:

```php
class TestController extends Controller
{
    function test_consumer () {
        test();
    }
}
class Handler
 {
     public function __invoke(Message $message){
       // Handle your message here
    }
 }
```
```php
 function test() {
     $consumer = Kafka::createConsumer()->subscribe(['test-topic'])
    ->withHandler(Handler::class)
    ->build();

    $consumer->consume();
    
    return $consumer;
}
```

**Comment by mateusjunges** [comment]
Hi @maquib

I found some errors in your consumer code:
- 1. The `->withHandler()` method should receive a `new Handler`, instead of `Handler::class`
- 2. If you use the consumer without the `->withMaxMessages()`, your controller will never return, since it will keep consuming messages until it throws an exception. In general, kafka messages should be consumed using background processing (like laravel commands).

**Comment by maquib** [comment]
Hello @mateusjunges 
I used but didn't work 
For better understand Please give me a sample code

**Comment by mateusjunges** [comment]
I personally never used Consumers within controllers, so i don't have a working example. I'll provide you an example project with instructions to execute it:

Go to [this repository](https://github.com/mateusjunges/laravel-kafka-example)

You need to clone it to your local machine, install the dependencies and view the readme instructions to produce/consume messages.

The `TestHandler` class is responsible for handling the consumed messages. For now, it simply logs the messages into `storage/logs/laravel.log`, but it's a working example.
