### ISSUE TITLE
Consumer not Running in Laravel

### ISSUE THREAD

**Issue by pawan-khade** [mateusjunges/laravel-kafka#6]
```php
<?php

use Illuminate\Support\Facades\Route;
use Junges\Kafka\Facades\Kafka;

Route::get('/', function () {
    $consumer = Kafka::createConsumer('0',['warning'])->withConsumerGroupId('foo')->build();
    $consumer->consume();
});
?>
```
what to add to get consumed message in this code?

**Comment by mateusjunges** [comment]
Hello @pawan-khade, the message is not returned in `consume` method. You must create a `handler` class, which will be responsible for handling the message. Please, read the [configuring message handlers](https://github.com/mateusjunges/laravel-kafka#configuring-message-handlers) section of the package documentation. Basically, you create a invokable class, and use the `withHandler` method before building the consumer to tell Kafka which handler should be used:
```php
class Handler
{
    public function __invoke(\RdKafka\Message $message){
        // Handle your message here
    }
}

$consumer = Kafka::createConsumer('0',['warning'])->withConsumerGroupId('foo')
    ->withHandler(Handler::class)
    ->build();

$consumer->consume();
```
Hope it helps.
