### ISSUE TITLE
[QUESTION] what we are missing in consumer code?

### ISSUE THREAD

**Issue by mohdAarifkartrocket** [mateusjunges/laravel-kafka#60]
HI @mateusjunges we are trying to consume messages from confluent cloud's kafka cluster but we are unable to consume. we are using same credentials to publish the messges which is working fine.

This is our consumer code. please let us know what we are missing here. 

`<?php

namespace App\Console\Commands;

use App\Handlers\TestHandler;
use Illuminate\Console\Command;
use Junges\Kafka\Facades\Kafka;

class TestTopicConsumer extends Command
{
    protected $signature = 'kafka:test-consume';

    protected $description = 'Command description';

    public function handle(): void
    {
        $consumer = Kafka::createConsumer(['test_topic'], 'test-consumer', 'broker')
            ->subscribe('test_topic')
            ->withHandler(new TestHandler)
            ->withAutoCommit()
            ->withConsumerGroupId('test-consumer')
            ->withSasl(new \Junges\Kafka\Config\Sasl(
                password: 'kafka-api-secret',
                username: 'kafka-api-key',
                mechanisms: 'PLAIN',
                securityProtocol: 'SASL_SSL',
            ))
            ->build();

        $consumer->consume();
    }
}`

**Comment by mohdAarifkartrocket** [comment]
got the issue. i just send the sasl keys in ->withOptions() and its working fine.
here is the code example 
`$consumer = Kafka::createConsumer()
    ->withOptions([
        'sasl.username' => 'KAFKA-KEY',
        'sasl.password'=> 'KAFKA-SECRET',
        'sasl.mechanisms' => 'PLAIN',
        'security.protocol' => 'sasl_ssl'
    ])
    ->subscribe('test-topic')
    ->withHandler(new TestHandler)
    ->withAutoCommit()
    ->withConsumerGroupId('test_consumer')
    ->build();
$consumer->consume();`

**Comment by mateusjunges** [comment]
Hey @mohdAarifkartrocket can you tell me which `laravel-kafka` you are using? This is an issue i already fixed in [#5c028bf](https://github.com/mateusjunges/laravel-kafka/commit/5c028bfd3f6588e411babe5429fa78dc89ed2a22). If it is still happening on LTS i have to take a look again.

**Comment by mohdAarifkartrocket** [comment]
mateusjunges/laravel-kafka v1.5.3
