### ISSUE TITLE
[FEATURE REQUEST] support for php7. 4^ versions

### ISSUE THREAD

**Issue by AarifAbdal** [mateusjunges/laravel-kafka#61]
Hi @mateusjunges 

Is there any plan to make this package supportive for php7. 4^ versions. 

Thanks and regards.

**Comment by mateusjunges** [comment]
Hi @AarifAbdal, no, currently i have no time available for rewrite this package for 7.4. It was built o solve an issue i had with kafka while working on big projects. I'm glad i'm able to help other peoples with this code, but adding php 7.4 support will take at least a week, time i don't have right now. Feel free to fork this project and release a new version with 7.4 support. I can help you if you have any issues, but it's something i can't prioritize right now. Thanks!

**Comment by AarifAbdal** [comment]
Hi @mateusjunges can you please guide me what type of changes I have to made to make it working for php7. 4
