### ISSUE TITLE
[FEATURE REQUEST] support for php 7.4

### ISSUE THREAD

**Issue by DBTK1990** [mateusjunges/laravel-kafka#62]
**Is your feature request related to a problem? Please describe.**
run application on env with php 7.4

**Describe the solution you'd like**
support for php 7.4

**Describe alternatives you've considered**
run transpiler on your code to adjust it to php 7.4

**Additional context**
you can do this easily with rector/rector package 
i forked your repo you can take a look ([my-forked-repo](https://github.com/DBTK1990/laravel-kafka)) at my config for the rector compiler 
i got only one failed test , something with one of the option so not so bad

please consider this

**Comment by mateusjunges** [comment]
Hi @DBTK1990 
I have no plans to add PHP 7.4 support for this project, Personally i think php 8 has a much cleaner code syntax and is much easier to maintain. You can release your fork as a new version for this project, supporting PHP 7.4. If you do it, let me know and i'll pin this issue so people who wants to use this package on php 7.4 can find your code.
