### ISSUE TITLE
Installation error ext-rdkafka

### ISSUE THREAD

**Issue by Ceater** [mateusjunges/laravel-kafka#63]
Hello, i have problem with ext-rdkafka when install..

i use PHP 8.1

i've installed librdkafka via homebrew, here is my brew info

> librdkafka: stable 1.8.2 (bottled), HEAD
> Apache Kafka C/C++ library
> https://github.com/edenhill/librdkafka
> /opt/homebrew/Cellar/librdkafka/1.8.2 (36 files, 4.9MB) *
>   Poured from bottle on 2022-01-06 at 13:00:56
> From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/librdkafka.rb
> License: BSD-2-Clause
> ==> Dependencies
> Build: pkg-config ✘, python@3.10 ✘
> Required: lz4 ✔, lzlib ✔, openssl@1.1 ✔, zstd ✔
> ==> Options
> --HEAD
> 	Install HEAD version
> ==> Analytics
> install: 5,617 (30 days), 28,011 (90 days), 101,246 (365 days)
> install-on-request: 3,609 (30 days), 19,617 (90 days), 66,506 (365 days)
> build-error: 0 (30 days)

and when in run composer require mateusjunges/laravel-kafka, i got this error

> [InvalidArgumentException]                                                                             
> Package mateusjunges/laravel-kafka has requirements incompatible with your PHP version, PHP extension  
> s and Composer version:                                                                                
>   - mateusjunges/laravel-kafka v1.5.3 requires ext-rdkafka ^5.0|^4.0 but it is not present. 

can someone help me, how to fix this error?
thx

**Comment by mateusjunges** [comment]
@Ceater This package required the `ext-rdkafka` php extension. On linux, you can install it using pecl: https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka.installation.pecl.html

**Comment by Ceater** [comment]
after install sudo pecl install rdkafka, i got this error that when i search people said, i need to install librdkafka, but i already install it.

<img width="795" alt="Screen Shot 2022-01-07 at 10 16 12" src="https://user-images.githubusercontent.com/16059037/148485754-6647714d-b2aa-4ee8-a13b-37ba27847cc3.png">

**Comment by rtuin** [comment]
Assuming you're using macOS, since you're referencing homebrew: you don't need to run sudo when installing PECL extensions.

I know this works on recent macOS installations:
```
brew install librdkafka
pecl install rdkafka
```

Does this work for you?

**Comment by Ceater** [comment]
librdkafka is installed on system, you can check from my 1st post. i install using this command

brew install librdkafka

while installing rdkafka without sudo, generate error permission denied.

<img width="575" alt="Screen Shot 2022-01-08 at 09 19 12" src="https://user-images.githubusercontent.com/16059037/148627898-1fc89134-759e-4ffc-bbdf-482b342f8d60.png">

**Comment by mateusjunges** [comment]
Solved on #64
