### ISSUE TITLE
[QUESTION] How to consume with offset?

### ISSUE THREAD

**Issue by Ceater** [mateusjunges/laravel-kafka#65]
hello, i want to know how to consume old massage inside broker?

i need to do this because i want to store data inside broker massage so the data itself will store inside kafka memory. and i need to reconsume that data as many times as possible.

**Comment by mateusjunges** [comment]
this package does not provide a way to change the consumer offset manually. You can use the `offset_reset` equals to `earliest` configuration option to start consuming at the first message published at a given topic.
Also, kafka isn't like a database, so i really don't recommend you to store data in kafka. You can store what you need in the database while processing kafka messages, so you don't need to reprocess everything everytime you want some data.

**Comment by Ceater** [comment]
hmm, ok thanks for answer..
i wonder if we can access old massage.
