### ISSUE TITLE
[BUG] - Consumer not getting messages with php rdkafka extension version 6.0.0 

### ISSUE THREAD

**Issue by joaoccmatos** [mateusjunges/laravel-kafka#67]
There has been a new release of rdkafka on 2022-01-07 and since then consumer can't process messages, producing the following error: "throwable":{"class":"Error","message":"Typed property RdKafka\\Message::$headers must not be accessed before initialization" ,"code":0,"file":"/var/www/html/vendor/mateusjunges/laravel-kafka/src/Consumers/Consumer.php:282

For everyone having the same error, you should install rdkafka-5.0.2.

**Comment by mateusjunges** [comment]
Good morning @joaoccmatos 
Actually it is not a bug, since `laravel-kafka` supports `ext-rdkafka` versions `^4.0^ and `^5.0`. There is a PR open to add support for `v6.0`, and i'm currently building the test images on docker for that version. Thanks!

**Comment by mateusjunges** [comment]
@joaoccmatos released on [v1.6.0](https://github.com/mateusjunges/laravel-kafka/tree/v1.6.0)

**Comment by shazaman23** [comment]
As a note on this, I was getting this error with my implementation of rdkafka (v6.0.0) and I found that I only get this error when the headers object in kafka is empty `{}`. When I had any header set, the message comes through on the consumer just fine.
