### ISSUE TITLE
[QUESTION] Offset Commit - Clarification

### ISSUE THREAD

**Issue by shazaman23** [mateusjunges/laravel-kafka#74]
I'm just getting started with this package. I've gone through the documentation and parts of the code surrounding consuming a message and using committers. From other research into librdkafka, I know that under the covers the offset committal process is controlled by a background thread so there is a chance that an offset could be committed to kafka before the message was successfully consumed. i.e. Kafka could think a message got received and is told to move on when really the message failed so you lose out on 'At Least Once' processing. ([librdkafka doc reference](https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#at-least-once-processing)) 

My question is around the offset commit functionality in your package. When I was looking through the default `DefaultCommitterFactory` and the consumer code, it looked like by default the consumer will wait until the message successfully processes before trying a commit. If it fails processing, it will try to commit to the dead letter queue where as if it was successful it will commit the offset AFTER PROCESSING to the original topic. Is my understanding here correct? 

If not, can you explain more what is happening when commitMessage runs or when you set up a topic using `->withAutoCommit()`?

**Comment by mateusjunges** [comment]
Hi @shazaman23, sorry for my late response i'm having a really busy week. Your explanation is correct. When you enable auto commit, the kafka consumer commits the offset periodically when polling batches

**Comment by mateusjunges** [comment]
@shazaman23 i'm closing this but feel free to reopen or create a new issue if you still have any questions. Thank you!
