### ISSUE TITLE
[QUESTION] Undefined constant Junges\Kafka\RD_KAFKA_PARTITION_UA

### ISSUE THREAD

**Issue by lanied** [mateusjunges/laravel-kafka#80]
Hi, I get this error
![image](https://user-images.githubusercontent.com/48638777/154851725-b9c48a83-4ccb-45ee-86ea-81fe016095bd.png)

![image](https://user-images.githubusercontent.com/48638777/154851533-cf5850c3-6efe-44f8-84cc-7dee6a7efd00.png)

i'm using this rdkafka version
![image](https://user-images.githubusercontent.com/48638777/154851635-453169d3-edd2-4a86-bd31-ba77987a98e4.png)

my s.o ubuntu 20.04 lts im using the lastest 1.6 ver.

**Comment by lanied** [comment]
sorry i solved it 

I had not configured the extension in php-fpm config.

**Comment by tassiovale** [comment]
> sorry i solved it
> 
> I had not configured the extension in php-fpm config.

Could you please share it?
