### ISSUE TITLE
[BUG] incorrect configuration setting in KafkaConsumerCommand

### ISSUE THREAD

**Issue by dbfun** [mateusjunges/laravel-kafka#81]
**Describe the bug**
The KafkaConsumerCommand class uses the value `kafka.group_id`, although it is defined as `kafka.consumer_group_id` in the configuration file `kafka.php`.

**How to fix**
Need to replace this part of the code in KafkaConsumerCommand

```
'groupId' => config('kafka.group_id'),
```

to this line

```
'groupId' => config('kafka.consumer_group_id'),
```

**Comment by mateusjunges** [comment]
@dbfun released on [v1.6.4](https://github.com/mateusjunges/laravel-kafka/releases/tag/v1.6.4)
