### ISSUE TITLE
[FEATURE REQUEST] Mocking Kafka consumer

### ISSUE THREAD

**Issue by juliancms** [mateusjunges/laravel-kafka#89]
Are you planning on adding helpers for mocking the kafka consumer?

**Comment by mateusjunges** [comment]
Its on my roadmap,but i'm really busy this past weeks, so i really don't have time to do at least for the next month. Feel free to submit a PR implementing this feature if you want to.

**Comment by mateusjunges** [comment]
Hey @juliancms, please have a look at #107 and let me know your thoughts on it.

**Comment by juliancms** [comment]
@mateusjunges it looks good for me, thank you very much for notifying
