### ISSUE TITLE
[QUESTION] - Custom Offset storage

### ISSUE THREAD

**Issue by AdrianoRamalho21** [mateusjunges/laravel-kafka#99]
Quick question, is it possible to save the offset by consumer in, for example, Redis or DB?
And, when the broker shuts down and comes back up, is it possible to tell the consumer to start consuming messages from that specific offset?

Let's say I have a laravel Artisan command that builds the following consumer :

```php
public function handle()
{
    $topics = [
        'fake-topic-1',
        'fake-topic-2',
        'fake-topic-3'
    ];

    $cachedRegistry = new CachedRegistry(
        new BlockingRegistry(
            new PromisingRegistry(
                new Client(['base_uri' => 'https://fake-schema-registry.com'])
            )
        ),
        new AvroObjectCacheAdapter()
    );        

    $registry = new \Junges\Kafka\Message\Registry\AvroSchemaRegistry($cachedRegistry);
    $recordSerializer = new RecordSerializer($cachedRegistry);

    foreach ($topics as $topic) 
    {
        $registry->addKeySchemaMappingForTopic(
            $topic,
            new \Junges\Kafka\Message\KafkaAvroSchema($topic . '-key')
        );
        $registry->addBodySchemaMappingForTopic(
            $topic,
            new \Junges\Kafka\Message\KafkaAvroSchema($topic . '-value')
        );
    }

    $deserializer = new \Junges\Kafka\Message\Deserializers\AvroDeserializer($registry, $recordSerializer);

    $consumer = \Junges\Kafka\Facades\Kafka::createConsumer(
        $topics, 'fake-test-group', 'fake-broker.com:9999')
    ->withOptions([
        'security.protocol' => 'SSL',
        'ssl.ca.location' => storage_path() . '/client.keystore.crt',
        'ssl.keystore.location' => storage_path() . '/client.keystore.p12',
        'ssl.keystore.password' => 'fakePassword',
        'ssl.key.password' => 'fakePassword',
    ])
    ->withAutoCommit()
    ->usingDeserializer($deserializer)
    ->withHandler(function(\Junges\Kafka\Contracts\KafkaConsumerMessage $message) {

        KafkaMessagesJob::dispatch($message)->onQueue('kafka_messages_queue');

    }) 
    ->build();    
    
    $consumer->consume();
}
```

My problem now is that, from time to time, the "fake-broker.com:9999" shuts down and when it comes up again, it misses a few messages...

- `offset_reset` is set to `latest` ;
- The option `auto.commit.interval.ms` is not set on the `->withOptions()` method, so it is using the default value (5 seconds, I believe) ;
- `auto_commit` is set to `true` and the consumer is built with the option `->withAutoCommit()` as well ;

**Comment by mateusjunges** [comment]
Hi @AdrianoRamalho21 to be honest i've never had this use case, but from what i know about kafka, you typically starts either from earliest or the latest offset. If the consumer crashes, then all partitions of the crashed consumer will be reset to the last commited offset, and all messages arrived since the last commit will be read again. Kafka ensures `at least once` delivery, which means that no messages willbe missed, but duplicated can occur, so you should handle it in your app.

**Comment by mateusjunges** [comment]
@AdrianoRamalho21 sorry for the delay, i was very busy at work this past days. Currently, consuming from specific offset is no possible, since it is not implemented yet. I will take a look at this and possibly implement as a new feature, but don't expect it for the next few days.

**Comment by AdrianoRamalho21** [comment]
@mateusjunges no problem ;) Thank you, and I think it will be a useful new feature, in some particularly/specific cases.

No need to rush it tho :D

Thanks one more time, and you may close this issue.

Good work and have a nice day
